### ISSUE TITLE
Parsing estonian symbols

### ISSUE THREAD

**Issue by Kasparsu** [facebook/duckling#107]
Well I am trying to help out with estonian language. Im new to haskell so asking for help. anyway it seems that it won't match some of my languages special characters. as it turns them into alt codes aka `kümnes` becomes `k\252mnes` etc. Solution is easy enough to encode all the matches as well, but its harder to grasp and read then. Any other ideas? letters that might be issue in estonian are üäöõšž
they seem to be working in wit.io tho so I think it might be connected to docker container.

**Comment by patapizza** [comment]
Hi @Kasparsu,

How are you using Duckling? As a library, using the server example or something else?

It does work for me using the library and the server:
```
> debug (makeLocale ET Nothing) "Kolmkümmend kolm" [This Numeral]
integer 21..99 (Kolmkümmend kolm)
-- integer (20..90) (Kolmkümmend)
-- -- regex (Kolmkümmend)
-- integer (0..19) (kolm)
-- -- regex (kolm)
[Entity {dim = "number", body = "Kolmk\252mmend kolm", value = Object (fromList [("value",Number 33.0),("type",String "value")]), start = 0, end = 16}]
it :: [Entity]

$ curl -XPOST http://0.0.0.0:8000/parse --data 'locale=et_XX&text=Kolmkümmend kolm'
[{"dim":"number","body":"Kolmkümmend kolm","value":{"value":33,"type":"value"},"start":0,"end":16}]%
```

Feel free to reopen if you still experience the issue.

**Comment by Kasparsu** [comment]
Ah thats how locale is used.. it's kinda confusing.. will give your examples a try. wouldn't it make sense to use full locale `et_EE` instead of `et_XX` ?

**Comment by Kasparsu** [comment]
well it seems to do fine in server but in curl doesn't. I am using docker to run this so there might be something off in there.

`*Duckling.Debug> debug (makeLocale ET Nothing) "Kolmkümmend kolm" [This Numeral]
integer 21..99 (Kolmkümmend kolm)
-- integer (20..90) (Kolmkümmend)
-- -- regex (Kolmkümmend)
-- integer (0..19) (kolm)
-- -- regex (kolm)
[Entity {dim = "number", body = "Kolmk\252mmend kolm", value = Object (fromList [("value",Number 33.0),("type",String "value")]), start = 0, end = 16}]`


`$ curl -XPOST http://192.168.99.100:8000/parse --data 'locale=et_XX&text=Kolmkümmend kolm'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    34    0     0  100    34      0     34  0:00:01 --:--:--  0:00:01  2125
curl: (52) Empty reply from server`

**Comment by patapizza** [comment]
@Kasparsu: You can use `et_EE`, it would work too.
Hmm this doesn't seem like an issue from the server example - it would return an empty list (`[]`) if it doesn't find anything. Not sure it is related, but what is the output of the `locale` command?
