### ISSUE TITLE
Incorrect 'to' value while parsing duration/time interval

### ISSUE THREAD

**Issue by nsanthanam** [facebook/duckling#108]
Hi Duckling team,

I'm having some difficulty understanding Duckling's output for input that contains a duration/time interval - the end time is incorrect, and is consistently offset from the actual end time by 1 'grain of time', where 'grain' is either hour or minute.

For instance, when I run the command `curl -XPOST http://0.0.0.0:8000/parse --data 'text=i am available from 6 to 8 pm today'`, I receive the following response:
```
{
  "to":{"value":"2017-11-14T21:00:00.000-08:00","grain":"hour"},
  "from":{"value":"2017-11-14T18:00:00.000-08:00","grain":"hour"},
  "type":"interval"
}
```
For some reason, the `to` is set to 1 hour (`21:00`) after the end time I specify in the input (`20:00`). 

If I change the request to `curl -XPOST http://0.0.0.0:8000/parse --data 'text=i am available from 6 to 8:30 pm today'`, the response is:
```
{
  "to":{"value":"2017-11-14T20:31:00.000-08:00","grain":"minute"},
  "from":{"value":"2017-11-14T18:00:00.000-08:00","grain":"minute"},
  "type":"interval"
}
```
Here `to` is set to 1 minute after the end time (`20:31`), instead of `20:30`. Guessing this is because of the grain at which the text is interpreted.

How do I change the code so that (in the server example) I get the `to` value to be set to the exact end time?

Thank you for being patient and helping out always!

**Comment by patapizza** [comment]
Hi @nsanthanam,

For `Time`, Duckling returns left-closed, right-open intervals (exclusive upper limit).
To get the inclusive upper limit, you'd need to do something like: `to - grain`.

Hope this helps.
