### ISSUE TITLE
X k€ and X M€ are not recognized as `money` in French

### ISSUE THREAD

**Issue by raphael0202** [facebook/duckling#109]
In French, it is common to use X k€ (or Xk€) as X thousands euros, or X M€ as X millions euros.
Currently, duckling does not recognize those as entities of type `money`.

**Comment by patapizza** [comment]
Hi @raphael0202,

I can't repro the issue:
```
$ curl -XPOST http://0.0.0.0:8000/parse --data 'locale=fr_XX&text=20 k€'
[{"dim":"amount-of-money","body":"20 k€","value":{"value":20000,"type":"value","unit":"EUR"},"start":0,"end":5}]%       

$ curl -XPOST http://0.0.0.0:8000/parse --data 'locale=fr_XX&text=20 M€'
[{"dim":"amount-of-money","body":"20 M€","value":{"value":20000000,"type":"value","unit":"EUR"},"start":0,"end":5}]%
```

Can you share a curl example that doesn't work?

**Comment by raphael0202** [comment]
Hello,
Indeed the issue came from my code.
I'm sorry about the false report.
