### ISSUE TITLE
Problems with numeral on PT rules

### ISSUE THREAD

**Issue by alexst07** [facebook/duckling#113]
When I write "dois mil e duzentos" the result should be 2200, but duckling recognize the numbers separated and give the result:

`[{"dim":"number","body":"dois","value":{"value":2,"type":"value"},"start":0,"end":4},{"dim":"number","body":"mil","value":{"value":1000,"type":"value"},"start":5,"end":8},{"dim":"time","body":"mil","value":{"values":[],"value":"1000-01-01T00:00:00.000-07:53","grain":"year","type":"value"},"start":5,"end":8},{"dim":"number","body":"duzentos","value":{"value":200,"type":"value"},"start":11,"end":19}]`

**Comment by patapizza** [comment]
Thanks for reporting @alexst07.

Any chance you can get a stab at this? Relevant files are [here](https://github.com/facebook/duckling/tree/master/Duckling/Numeral/PT).

**Comment by alexst07** [comment]
Yes, I fixed the bug, I will try to do some improvements on code, as I don't have much experience with Haskell I have to search a little, but I will make a request until this sunday.

**Comment by alexst07** [comment]
Fixed on https://github.com/facebook/duckling/pull/117/commits
