### ISSUE TITLE
Unable to add Numeral Dimension for a new language.

### ISSUE THREAD

**Issue by NewInfinite007** [facebook/duckling#118]
Hi,

   I am trying to add Numeral Dimension to Facebook Duckling for a new Language(Hindi Language). I tried following steps provided in [this example](https://github.com/facebook/duckling/commit/24d3f199768be970149412c95b1c1bf5d76f8240) but the Tests fail for the new Language. I get this error: `HI Tests
        Corpus Tests:              FAIL
          empty result on ("\2358\2370\2344\2381\2351",[])
`  I also tried to print the tokens which is the '[]' after "\2358\2370\2344\2381\2351"
After tracing the error, I found out that it is an assertion error from "tests/Duckling/Testing/Asserts.hs" in 'makeCorpusTest' . Could you please enlighten me regarding this issue?

Thanks in Advance.

**Comment by patapizza** [comment]
Hi @NewInfinite007,

Thanks for tackling this! Can you submit a PR as a WIP? It would be easier to debug.

**Comment by NewInfinite007** [comment]
Hi @patapizza 
I tried modifying code pertinent to HI language. Now the tests are passing. This is regarding the commit : 
[3c1f92128c379a70658a81a636b91dae0230ab26](https://github.com/facebook/duckling/pull/119/commits/3c1f92128c379a70658a81a636b91dae0230ab26).
I tried to build and run the model, but I get an empty list in return when I try examples like : 'शून्य','एक'  etc., which I specified in the corpus file.
Am I missing something? could you please help me with this? Also do I need to raise a new issue to solve this problem?

Thanks in Advance.

**Comment by patapizza** [comment]
@NewInfinite007 Commented directly on the PR. Let's continue the conversation there :)
