### ISSUE TITLE
get a typed output instead of a stringified one

### ISSUE THREAD

**Issue by Mudada** [facebook/duckling#121]
Hello guys,

we actually use Duckling to parse some poor checked csv to get phoneNumbers.
At this moment, we are first parsing with duckling which find the number and after we are parsing the duckling's output to type it. Since it is typed in duckling but not in the output we wanted to know if it was possible to get the typed value insted of the stringyfied one. Something like ``parsePhone :: Text -> Context  -> [Dimension]`` for exemple.

If it's not, we wanted to know why you choosed to do a one block treatment instead of splitting it in two (one part "core" which identity and type the input and a part "api" which get type and return the actual value output).

**Comment by patapizza** [comment]
Hey @Mudada,

Indeed that's a good point. Let me see if we can get typed outputs.

**Comment by patapizza** [comment]
Sorry I couldn't get around this - placing up for grabs.

**Comment by patapizza** [comment]
@zliu41 is on it
