### ISSUE TITLE
Date formatted as d/mm/yy not being recognized

### ISSUE THREAD

**Issue by seme0021** [facebook/duckling#124]
I'd expect the incorrect example below to return a date - thoughts?

Incorrect:
`6/27/18` returns: `[{"dim":"number","body":"6/27","value":{"value":0.2222222222222222,"type":"value"},"start":0,"end":4},{"dim":"number","body":"18","value":{"value":18,"type":"value"},"start":5,"end":7}]`

Correct:
`6/27/2018` returns `[{"dim":"number","body":"6/27","value":{"value":0.2222222222222222,"type":"value"},"start":0,"end":4},{"dim":"number","body":"2018","value":{"value":2018,"type":"value"},"start":5,"end":9},{"dim":"time","body":"2018","value":{"values":[{"value":"2018-01-01T00:00:00.000-08:00","grain":"year","type":"value"}],"value":"2018-01-01T00:00:00.000-08:00","grain":"year","type":"value"},"start":5,"end":9}]`

**Comment by panagosg7** [comment]
Hi @seme0021,

I'm trying to reproduce your result, but I think that the result I'm getting is the expected one. Here's the command I'm issuing:
```
Duckling.Debug> debug (makeLocale EN $ Just US) "6/27/18" [This Time]
mm/dd/yyyy (6/27/18)
-- regex (6/27/18)
[Entity {dim = "time", body = "6/27/18", value = Object (fromList [("values",Array [Object (fromList [("value",String "2018-06-27T00:00:00.000-02:00"),("grain",String "day"),("type",String "value")])]),("value",String "2018-06-27T00:00:00.000-02:00"),("grain",String "day"),("type",String "value")]), start = 0, end = 7}]
```
Can you provide some more information about how to reproduce your result?

**Comment by seme0021** [comment]
My bad, I was using `us_GB` as locale instead of US.

Thanks for following up.
