### ISSUE TITLE
French Date Day and Month always return 01-01 (January first)

### ISSUE THREAD

**Issue by kwims** [facebook/duckling#129]
When I submit "15 novembre 2017" on https://duckling.wit.ai/, I get "Wednesday, 15 November 2017" and that is the correct answer.

When I run it on facebook/duckling locally, I get the following.
`curl -XPOST http://localhost:8000/parse --data 'locale=fr&text=15 novembre 2017'
[{"dim":"number","body":"15","value":{"value":15,"type":"value"},"start":0,"end":2},{"dim":"number","body":"2017","value":{"value":2017,"type":"value"},"start":12,"end":16},{"dim":"time","body":"2017","value":{"values":[{"value":"2017-01-01T00:00:00.000-08:00","grain":"year","type":"value"}],"value":"2017-01-01T00:00:00.000-08:00","grain":"year","type":"value"},"start":12,"end":16}]
`

Any help greatly appreciated

**Comment by patapizza** [comment]
Hi @kwims,

It's because the `locale` isn't properly set: it should be `fr_FR` (or `fr_XX`, etc.).

```
$ curl -XPOST http://0.0.0.0:8000/parse --data 'locale=fr_XX&text=15 novembre 2017'
[{"dim":"time","body":"15 novembre 2017","value":{"values":[{"value":"2017-11-15T00:00:00.000-08:00","grain":"day","type":"value"}],"value":"2017-11-15T00:00:00.000-08:00","grain":"day","type":"value"},"start":0,"end":16}]
```

**Comment by kwims** [comment]
```
 curl -XPOST http://localhost:8000/parse --data 'locale=fr_FR&text=15 novembre 2017'
[{"dim":"number","body":"15","value":{"value":15,"type":"value"},"start":0,"end":2},{"dim":"number","body":"2017","value":{"value":2017,"type":"value"},"start":12,"end":16},{"dim":"time","body":"2017","value":{"values":[{"value":"2017-01-01T00:00:00.000-08:00","grain":"year","type":"value"}],"value":"2017-01-01T00:00:00.000-08:00","grain":"year","type":"value"},"start":12,"end":16}]
```
I just tried and I have the same problem. Anything else you can think of @patapizza  ?

**Comment by kwims** [comment]
Never mind, My docker was not being compile with the latest version. I now get the right result.
