### ISSUE TITLE
Ability to specify reference time for parsing

### ISSUE THREAD

**Issue by vinvinod** [facebook/duckling#132]
This is a feature request for the web server.

The `/parse` end point in the server should also accept a parameter `time` or `reftime` which specifies the time in milliseconds. This specifies the reference time with which the given text string is to be parsed. This along with `timezone` info may be used to construct the `referenceTime` using the function `makeRefTime`. 

If the time specifying parameter is not present in the request, we can construct the `referenceTime` to using `currentReftime`, the way it is now.

This will be helpful when parsing a conversation which has happened in the past.

**Comment by patapizza** [comment]
@vinvinod Any chance you can give it a shot? :)

**Comment by vinvinod** [comment]
Not anytime soon! I will have to learn haskell 😄

**Comment by vinvinod** [comment]
@patapizza Please check PR #133 
I don't know how bad it is!

**Comment by patapizza** [comment]
@vinvinod Thanks, will look next year ;-)

**Comment by patapizza** [comment]
@vinvinod Before we can do anything, please sign the CLA.

**Comment by vinvinod** [comment]
Just signed the CLA.
