### ISSUE TITLE
"from 3pm" incorrectly parsed

### ISSUE THREAD

**Issue by fil090302** [facebook/duckling#136]
Is there any reason why "from 3pm" gives the same result as "3pm" instead of "since 3pm"?

**Comment by patapizza** [comment]
@fil090302: Seems like this is not encoded in the rules, thus it parses "3pm" only.
The fix seems [easy enough](https://github.com/facebook/duckling/blob/master/Duckling/Time/EN/Rules.hs#L1193), do you want to submit a PR?

**Comment by fil090302** [comment]
@patapizza Can you please check PR #138?
