### ISSUE TITLE
Swedish datetime parser fails in certain cases

### ISSUE THREAD

**Issue by magnusburton** [facebook/duckling#140]
The Swedish DateTime parser fails when we have a date followed by time in the following format. In Swedish it's common to prepend the time part of the DateTime object by `kl.` or `kl` (see below).

`2018-02-28 kl 16:00`
`2017-06-19 kl 7:00` (in the am)
`2017-05-2 kl. 07:00`

It works if we were to remove `kl.` and `kl` from the object:

`2018-02-28 16:00`
`2017-06-19 7:00` (in the am)
`2017-05-2 07:00`

I helped write the rules and corpus before you moved Duckling to Haskell so I have no idea on how to fix this. I suppose it's an easy fix and I'd appreciate any help!

**Comment by patapizza** [comment]
Hi @magnusburton,

How did you run Duckling? Did you pass the locale correctly?

I can't repro:

```
$ curl -XPOST http://0.0.0.0:8000/parse --data 'locale=sv_xx&text=2017-06-19 kl 7:00'
[{"dim":"time","body":"2017-06-19 kl 7:00","value":{"values":[],"value":"2017-06-19T07:00:00.000-07:00","grain":"minute","type":"value"},"start":0,"end":18}]

$ curl -XPOST http://0.0.0.0:8000/parse --data 'locale=sv_xx&text=2017-05-2 kl. 07:00'
[{"dim":"time","body":"2017-05-2 kl. 07:00","value":{"values":[],"value":"2017-05-02T07:00:00.000-07:00","grain":"minute","type":"value"},"start":0,"end":19}]
                                          
$ curl -XPOST http://0.0.0.0:8000/parse --data 'locale=sv_xx&text=2018-02-28 kl 16:00'
[{"dim":"time","body":"2018-02-28 kl 16:00","value":{"values":[{"value":"2018-02-28T16:00:00.000-08:00","grain":"minute","type":"value"}],"value":"2018-02-28T16:00:00.000-08:00","grain":"minute","type":"value"},"start":0,"end":19}]
```

**Comment by magnusburton** [comment]
@patapizza 

I ran Duckling through the wit ui. Figured it might be an issue with Duckling instead of being an issue related to wit.ai

**Comment by patapizza** [comment]
@magnusburton I can't repro there either. Is your app language set to Swedish? Feel free to open a ticket [here](https://github.com/wit-ai/wit/issues) if you still experience issues.
