### ISSUE TITLE
Between two numbers only returns dates

### ISSUE THREAD

**Issue by seme0021** [facebook/duckling#142]
Q1: Is there a way to force or limit output to a specific dimension like `number`

Q2: There seems to be a bug when running `curl -XPOST http://0.0.0.0:8000/parse --data 'text=between 5 and 10'`

It only returns the `time` dimension, but should also return the `number` dimension values.

```
[{"dim":"time","body":"between 5 and 10","value":{"values":[{"to":{"value":"2018-01-17T23:00:00.000-08:00","grain":"hour"},"from":{"value":"2018-01-17T17:00:00.000-08:00","grain":"hour"},"type":"interval"},{"to":{"value":"2018-01-18T11:00:00.000-08:00","grain":"hour"},"from":{"value":"2018-01-18T05:00:00.000-08:00","grain":"hour"},"type":"interval"},{"to":{"value":"2018-01-18T23:00:00.000-08:00","grain":"hour"},"from":{"value":"2018-01-18T17:00:00.000-08:00","grain":"hour"},"type":"interval"}],"to":{"value":"2018-01-17T23:00:00.000-08:00","grain":"hour"},"from":{"value":"2018-01-17T17:00:00.000-08:00","grain":"hour"},"type":"interval"},"start":0,"end":16}]
```

Other cases to help debug:

`curl -XPOST http://0.0.0.0:8000/parse --data 'text=between 5 and 10k'` returns time only

`curl -XPOST http://0.0.0.0:8000/parse --data 'text=between 5k and 10k'` is accurate and returns distance and number.

**Comment by patapizza** [comment]
@seme0021 

Yes, you can provide the `dims` parameter to the server example. When unspecified, Duckling tries to run all dimensions. That's why you'd get `Time` for `between 5 and 10` but not for `between 5k and 10k`.

Example:
```
$ curl -XPOST http://0.0.0.0:8000/parse --data 'text=between 5 and 10&dims=["number"]'
[{"dim":"number","body":"5","value":{"value":5,"type":"value"},"start":8,"end":9},{"dim":"number","body":"10","value":{"value":10,"type":"value"},"start":14,"end":16}]
```

As a note, `between x and y` would ideally return a `Numeral` interval.
