### ISSUE TITLE
Support for IN locale on Numeral dimension

### ISSUE THREAD

**Issue by sanjredfield** [facebook/duckling#147]
I am interested in adding support for the IN locale on the Numeral dimension. I would like to do this because of differences between British / American English, and Indian English. Specifically, we use "lakh" and "crore" here, instead of "million" and "billion". The placement of commas within a number also differs for our locale. See https://en.wikipedia.org/wiki/Indian_numbering_system for more details. 

Before beginning to work on this issue, I wanted to check in on two things:

1. Is adding a new locale the right way of going about this? The same numbering system is also used in Pakistan, Bangladesh, and Nepal, so the locale specific code would have to be structured in a way that avoids duplication. If there is any similar example in the existing code base, it would be very helpful to be pointed towards it. 
2. Is anyone working on the same change already?

**Comment by patapizza** [comment]
@sanjredfield Thanks for reaching out.

Yes adding locales is the right way to do this. Changes need to ensure backward-compatibility.
In the current state of things, you'll probably need to duplicate the code for each locale (see https://github.com/facebook/duckling/commit/251028e6916cd02c8d6272d5a6ccf0e8cf1dc73f). This is for the sake of simplicity (all the locale-specific rules are in the same file, and each locale can be easily extended).
