### ISSUE TITLE
Bug on parsing amount-of-money in French

### ISSUE THREAD

**Issue by zsellami** [facebook/duckling#151]
Expected : 12 EUR
                  15 EUR
Extracted : 12.15 EUR
                  15 EUR
This is wrong : 
curl -XPOST http://0.0.0.0:8000/parse --data 'locale=fr_FR&text=Les frais de mission entre 12 euros et 15 euros'
[{"dim":"amount-of-money","body":"12 euros et 15","value":{"value":12.15,"type":"value","unit":"EUR"},"start":27,"end":41},{"dim":"amount-of-money","body":"15 euros","value":{"value":15,"type":"value","unit":"EUR"},"start":39,"end":47}]

**Comment by panagosg7** [comment]
Hi @zsellami! Thanks for bringing up the issue! Have you tried to come up with a fix? PRs are welcome :)

**Comment by zsellami** [comment]
Hi @panagosg7 . I tried a solution on my PC. The problem is with the ruleIntersectAndNumeral rule on FR Rules.hs.
I commented the call line instruction at the end of the file and the problem was resolved for me.
At the end, I think we need another rule to deal with "AmountOfMoney Interval" because my sample concern a money interval not a separate value

**Comment by panagosg7** [comment]
Fixed by https://github.com/facebook/duckling/commit/7a89ced6db8e23f1d28c66a91e9af1432f2d33ab.
