### ISSUE TITLE
"2017/02/20" is incorrectly classified as number

### ISSUE THREAD

**Issue by jgopalap** [facebook/duckling#154]
The result of the following curl operation

curl -XPOST http://0.0.0.0:8000/parse --data 'locale=en_US&text=2017/02/20&tz=America/Toronto'

returns the following

[{"dim":"number","body":"2017/02","value":{"value":1008.5,"type":"value"},"start":0,"end":7},{"dim":"number","body":"20","value":{"value":20,"type":"value"},"start":8,"end":10}]

This appears to be a misclassification.  I would've expected this to return a time dimension with value as "2017-02-20T00:00:00.000-05:00".

**Comment by kenpropel** [comment]
Typical formatting would be: (and these are parsed fine)

- yyyy-mm-dd : 2017-02-20
- m/d/yyyy : 2/20/2017 or 02/20/2017

(see: [Date notations in US](https://en.wikipedia.org/wiki/Date_and_time_notation_in_the_United_States))

From my experience in the U.S., I've yet to face a situation someone would put year in front using a `/` notation. But maybe it's just me?

**Comment by jgopalap** [comment]
That seems fair, although it is somewhat unsatisfying to see the a date being misclassified as a number :).

**Comment by kenpropel** [comment]
@jgopalap I hear ya. This might require a whole new dimension called `Clump` or something for undefined text. But maybe it's not what duckling is meant to be, I'm not sure. Example I run into is parsing this: `license G085WBW3G expires tomorrow`

```json
[
  {
    "dim":"number",
    "body":"085",
    "value":{
      "value":85,
      "type":"value"
    },
    "start":9,
    "end":12
  },
  {
    "dim":"quantity",
    "body":"3G",
    "value":{
      "value":3,
      "type":"value",
      "unit":"gram"
    },
    "start":15,
    "end":17
  },
  {
    "dim":"number",
    "body":"3G",
    "value":{
      "value":3000000000,
      "type":"value"
    },
    "start":15,
    "end":17
  },
  {
    "dim":"time",
    "body":"tomorrow",
    "value":{
      "values":[
        {
          "value":"2018-02-15T00:00:00.000-08:00",
          "grain":"day",
          "type":"value"
        }
      ],
      "value":"2018-02-15T00:00:00.000-08:00",
      "grain":"day",
      "type":"value"
    },
    "start":26,
    "end":34
  }
]
```

This could be something like a license plate number or software key. Not ideal, but I take it as I have to always process text myself as well as duckling and have a logic that picks what makes most sense. Curious how others approach these.

**Comment by panagosg7** [comment]
Exactly as @kenpropel said. We could accept a PR for a country with a bit more evidence that this format is used :)

Closing for now.
