### ISSUE TITLE
Not Capturing URL Fragment

### ISSUE THREAD

**Issue by kenpropel** [facebook/duckling#155]
Bug report of not capturing full URL. (from [wit-ai](https://github.com/wit-ai/wit/issues/965))

Parsing excludes URL **fragment** at the end. (What is a fragment? It's the optional `#header` at the end of some URLs. See [URI](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax).)

Example text sent to Wit app with `wit/url` as an entity:
`take a look at this url: https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax`
Response from Wit:
```json
{
  "_text": "take a look at this url: https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax",
  "entities": {
    "url": [
      {
        "confidence": 0.96785722222222,
        "domain": "en.wikipedia.org",
        "value": "https://en.wikipedia.org/wiki/Uniform_Resource_Identifier",
        "_entity": "url",
        "_body": "https://en.wikipedia.org/wiki/Uniform_Resource_Identifier",
        "_start": 25,
        "_end": 82
      }
    ],
  },
  "msg_id": "1234567890"
}
```

Expected to include fragment like so:
```json
{
  "value": "https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax",
  "_body": "https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax"
}
```

**Comment by patapizza** [comment]
Thanks for reporting @kenpropel. Would you be able to submit a patch?

**Comment by kenpropel** [comment]
@patapizza I'll have to admit I've never done Haskell programming so as much as I would like to help, if someone else can do it that's probably better.

But I'm guessing it's the regex patterns in this file:
https://github.com/facebook/duckling/blob/master/Duckling/Url/Rules.hs

If I can figure it out, I'll submit. If you or someone ends up fixing it, I'd be grateful!

**Comment by patapizza** [comment]
Ok I'm on it :)
