### ISSUE TITLE
Consecutive entities in the sentence having same labels are being clubbed together.

### ISSUE THREAD

**Issue by monika1800** [facebook/duckling#158]
For example, If my sentence is Redeem Investments in ABC Funds. Redeem and Investments both are individual terms categorised under the label "action". Instead of recognising both the terms separately it just club the consecutive terms with same entity together and makes it "Redeem Investments" instead.

This was working perfectly fine till last week. Dont know what happened after that. This is happening for almost all the label where consecutive terms are having same label identified by wit.

**Comment by patapizza** [comment]
Hi @monika1800, this is a Wit.ai issue. Please report this [here](https://github.com/wit-ai/wit/issues). Relevant ticket: https://github.com/wit-ai/wit/issues/973

**Comment by monika1800** [comment]
Sure. @patapizza
