### ISSUE TITLE
Incorrect response for pre-defined entity "wit/amount_of_money"

### ISSUE THREAD

**Issue by nvkirankumar** [facebook/duckling#159]
**Reporting a Bug**
**What is the current behavior?**
if we say "Pay Kiran1 10eur"
wit/amount_of_money is detecting that as 110EUR

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
(Scenario: when a name ends with a single digit number followed a 2digit amount of money, Then it is giving response as three digits currency [1st digit: the number with which it ended in the name and remaining two digits are same as given])

**What is the expected behavior?**
if we say "Pay Kiran1 10eur"
wit/amount_of_money is detecting that as 10EUR

**What is the App ID where you are experiencing this issue (if applicable)?**
AppId : 5a7305f4-73e4-4133-a119-e9523339bd90

**Comment by panagosg7** [comment]
Hi @nvkirankumar! We are working on a fix for this.

**Comment by panagosg7** [comment]
Fixed with 169df6b46bf922d31d8dbab4c73e84e3f505c51d
