### ISSUE TITLE
Not converting datetime into range

### ISSUE THREAD

**Issue by monika1800** [facebook/duckling#160]
Hi,

For the sentences involving terms such as "this week"/"this month", wit is not returning range in datetime entity. Rather it is giving the start date of the "week"/"month". Working fine in all other cases for "from" and "to" range in datetime.

**Comment by patapizza** [comment]
Hi @monika1800,

Both are precise points in time, with a different granularity (as opposed to intervals).
"this week" is a `Time` returning the beginning of the week as a value, with a `grain` of `week`. It is slightly different than `from Monday to Sunday`.
Likewise, "this month" is a `Time` returning the beginning of the month as a value, with a `grain` of `month` (different than `from the 1st to the 31st`).

You can use the `grain` information to convert it to a range if that is easier to handle in your application.

Hope this helps.

**Comment by monika1800** [comment]
@patapizza Thanks a lot.
