### ISSUE TITLE
curl ignores dim_filter and reference_time

### ISSUE THREAD

**Issue by AdrianSzymczak** [facebook/duckling#166]
Could you please help with duckling part which seems to work unproperly:
```
parseHandler :: HashMap Text TimeZoneSeries -> Snap ()
parseHandler tzs = do
  modifyResponse $ setHeader "Content-Type" "application/json"
  t <- getPostParam "text"
  l <- getPostParam "lang"
  ds <- getPostParam "dims"
  tz <- getPostParam "tz"
  loc <- getPostParam "locale"
  ref <- getPostParam "reftime"
```
Because extending curl (from the example)
`curl -XPOST http://0.0.0.0:8000/parse --data 'locale=en_GB&text=tomorrow at eight'`
with dim, dims, dim_filter, dim-filter etc. seems to have no effect.

Could you please enrich example curl command and if need be fix POST parsing, so that reference_time and dim_filter parameters would work?
When using old duckling model (python wrapper over jvm) it was possible to specify them without any issues, so it seems to be example server issue

**Comment by patapizza** [comment]
Hi @AdrianSzymczak,

Here's an example on how to query for both `dims` and `reftime`:

```
curl -XPOST http://0.0.0.0:8000/parse --data 'locale=en_XX&text=right now&dims=["time"]&reftime=1430604300000'
[{"body":"right now","start":0,"value":{"values":[{"value":"2015-05-02T15:05:00.000-07:00","grain":"second","type":"value"}],"value":"2015-05-02T15:05:00.000-07:00","grain":"second","type":"value"},"end":9,"dim":"time"}]
```
