### ISSUE TITLE
Amount of Money NL Support

### ISSUE THREAD

**Issue by souvikg10** [facebook/duckling#169]
Hello,
Is there someone working on the amount of Money matching for Dutch? 

I saw there is a rule made for NL but Amount of Money is not in the pipeline. is there someone who is maybe working on it?

**Comment by patapizza** [comment]
@souvikg10 Not that I know of, feel free to submit a PR! Bedankt!

**Comment by souvikg10** [comment]
Ok. I will add the rules for the money support. Btw do you know who manages the pypi package for the wrapper. Would be nice if we have a newer version there 😀

**Comment by souvikg10** [comment]
Hey @patapizza , I tried to compile but i receive an error on MacOs 
'linker error with gcc' 
I did follow the steps at issue #8  but it still didn't work for me. 
Installed PCRE, updated gcc and CLT for xcode. i still have the same error

'gcc failed in phase Linker.'

**Comment by patapizza** [comment]
@souvikg10 It seems like it's planned in *future* work: https://github.com/FraBle/python-duckling#future-work 

Can you share the full stack trace?

**Comment by souvikg10** [comment]
I did find the issue. It is linked to the new code I was trying to add.
I added two files 
AmountOfMoney/NL/Rules and Corpus then I added in Rules/NL.hs and imported the class. 

Did I miss something?

**Comment by souvikg10** [comment]
No worries, it works fine now. I am going to write some tests and make sure it catches most of the sentences in dutch regarding and then will make a PR. 

Cheers

**Comment by patapizza** [comment]
https://github.com/facebook/duckling/commit/ced73dcdcb04269a00e9be2f17742a80366630fa
