### ISSUE TITLE
Returns wrong time value when between two values

### ISSUE THREAD

**Issue by seme0021** [facebook/duckling#171]
Issue: when querying `between 1pm and 2pm` the `to` value is being returned as `"2018-04-11T15:00:00.000-07:00"` (3pm).

When querying `2pm` on it's own, the returned value is correct `"2018-04-11T14:00:00.000-07:00"` (2pm)

Input 1: `curl -XPOST http://0.0.0.0:8000/parse --data 'text=between 1pm and 2pm&dims=["time"]'`

Result 1: ```[{"body":"between 1pm and 2pm","start":0,"value":{"values":[{"to":{"value":"2018-04-10T15:00:00.000-07:00","grain":"hour"},"from":{"value":"2018-04-10T13:00:00.000-07:00","grain":"hour"},"type":"interval"},{"to":{"value":"2018-04-11T15:00:00.000-07:00","grain":"hour"},"from":{"value":"2018-04-11T13:00:00.000-07:00","grain":"hour"},"type":"interval"},{"to":{"value":"2018-04-12T15:00:00.000-07:00","grain":"hour"},"from":{"value":"2018-04-12T13:00:00.000-07:00","grain":"hour"},"type":"interval"}],"to":{"value":"2018-04-10T15:00:00.000-07:00","grain":"hour"},"from":{"value":"2018-04-10T13:00:00.000-07:00","grain":"hour"},"type":"interval"},"end":19,"dim":"time","latent":false}]```

Input 2: `curl -XPOST http://0.0.0.0:8000/parse --data 'text=2pm&dims=["time"]'`

Result 2: ```[{"body":"2pm","start":0,"value":{"values":[{"value":"2018-04-10T14:00:00.000-07:00","grain":"hour","type":"value"},{"value":"2018-04-11T14:00:00.000-07:00","grain":"hour","type":"value"},{"value":"2018-04-12T14:00:00.000-07:00","grain":"hour","type":"value"}],"value":"2018-04-10T14:00:00.000-07:00","grain":"hour","type":"value"},"end":3,"dim":"time","latent":false}]```

**Comment by patapizza** [comment]
Hi @seme0021, Duckling returns the outer bound for intervals. To get the inner bound, you can do outer bound - grain.

Hope this helps.

**Comment by seme0021** [comment]
Thanks @patapizza, how do I do that?

**Comment by patapizza** [comment]
@seme0021 Parsing the JSON, looking at the `grain` key and going one unit of grain backwards from `to.value` (using your language's standard datetime functions).

**Comment by seme0021** [comment]
Got it. Was just wondering if there was an API parameter that I could just set.

This works.
