### ISSUE TITLE
Specifying Time Grain

### ISSUE THREAD

**Issue by r-wheeler** [facebook/duckling#172]
Same issue as mentioned [here](https://github.com/facebook/duckling/issues/108) 
Just a little unclear as to what the solution is. 

When directly using haskell, how can I specify the time grain? 

Calling duckling with something like: 

`parse (Text.decodeUtf8 tx) context options dims

Thanks a ton

**Comment by patapizza** [comment]
Hi @r-wheeler,

Just to make sure, are you asking how to extract the time grain from the response?
This will be easier than reparsing JSON after #121 (upcoming).

**Comment by r-wheeler** [comment]
Is it possible to specify the time grain and /or  how do do I get the inclusive upper limit?

**Comment by patapizza** [comment]
Currently you'd need to parse the JSON value and look into the `grain` key.
After #121 this will be easier.

**Comment by zliu41** [comment]
with a3b3588, one can now access `TimeValue` in the output entities and change the grain.
