### ISSUE TITLE
Issue with Datetime

### ISSUE THREAD

**Issue by monika1800** [facebook/duckling#175]
Not able to convert in datetime sentences such as "2 thursdays back", "3 thursdays back" etc.

**Comment by patapizza** [comment]
Hi @monika1800, can you give it a shot? :)

**Comment by patapizza** [comment]
@ptek Thanks for this! Classifiers are actually required, you did well to include them in the commit.

**Comment by ptek** [comment]
I see. I have put the commit that includes the classifiers back into the PR then.

**Comment by haoxuany** [comment]
#180
