### ISSUE TITLE
[datetime] incorrect parsing of intervals

### ISSUE THREAD

**Issue by aicioara** [facebook/duckling#178]
I was just playing with wit.ai. I apologise if the prod version uses the old duckling. I appreciate further pointers. There is an issue with datetime interval extraction.

### To reproduce:
1. Create a new app in wit.ai
2. Enter the sentence `Meeting 3pm to 5pm tomorrow` 
3. Wait for duckling to automatically extract `3pm to 5pm tomorrow` and identify it as `wit/datetime`
4. Inspect the time that was extracted

### Expected:
```
from 16/04/2018, 15:00:00 to 16/04/2018, 17:00:00
```

### Actual:

```
from 16/04/2018, 15:00:00 to 16/04/2018, 18:00:00
```
Note that actual result is 15 to 18, while we expect 15 to 17.

### Screenshot:

![screenshot470](https://user-images.githubusercontent.com/3248682/38777321-b6f98730-40ae-11e8-82b2-f696f1b0f0d6.png)

**Comment by patapizza** [comment]
Hi @aicioara,

As mentioned in #171 and in #108, as well as in the [Wit.ai HTTP docs](https://wit.ai/docs/http/20170307#get--message-link):

"For datetime entities that are interval, Duckling always returns an exclusive upper limit."
