### ISSUE TITLE
"4A", "A4 A5" are incorrectly parsed into time

### ISSUE THREAD

**Issue by resec** [facebook/duckling#179]
Duckling is parsing "4A" into "4 am". and "4 A" from "A4 A5" as "4 am". I think all of these should be parsed as time.

```
text = "4A"
data = {"text":text, "lang":"EN", "dims":'["time","duration"]'}
requests.post(url="http://localhost:8000/parse", data=data).json()
```

> [{'body': '4A', 'start': 0, 'value': {'values': [{'value': '2018-04-17T04:00:00.000-07:00', 'grain': 'hour', 'type': 'value'}, {'value': '2018-04-18T04:00:00.000-07:00', 'grain': 'hour', 'type': 'value'}, {'value': '2018-04-19T04:00:00.000-07:00', 'grain': 'hour', 'type': 'value'}], 'value': '2018-04-17T04:00:00.000-07:00', 'grain': 'hour', 'type': 'value'}, 'end': 2, 'dim': 'time', 'latent': False}]

```
text = "A4 A5"
data = {"text":text, "lang":"EN", "dims":'["time","duration"]'}
requests.post(url="http://localhost:8000/parse", data=data).json()
```

> [{'body': '4 A', 'start': 1, 'value': {'values': [{'value': '2018-04-17T04:00:00.000-07:00', 'grain': 'hour', 'type': 'value'}, {'value': '2018-04-18T04:00:00.000-07:00', 'grain': 'hour', 'type': 'value'}, {'value': '2018-04-19T04:00:00.000-07:00', 'grain': 'hour', 'type': 'value'}], 'value': '2018-04-17T04:00:00.000-07:00', 'grain': 'hour', 'type': 'value'}, 'end': 4, 'dim': 'time', 'latent': False}]

**Comment by patapizza** [comment]
Thanks for reporting @resec!

**Comment by chinmay87** [comment]
Closed with https://github.com/facebook/duckling/commit/a7f83ffe6ab19b9019eaa2d583da975d0f1c1764
