### ISSUE TITLE
support about a week and a half ago

### ISSUE THREAD

**Issue by Downchuck** [facebook/duckling#185]
Currently, "about a week ago" is working, but "about a week and a half ago" is not. I'm not sure what scope we'd want to support in this project on conversational English, but I'll keep hunting.

**Comment by haoxuany** [comment]
Hi @Downchuck,
Yep, you're right. Would you like to take a stab at this? 😄

**Comment by haoxuany** [comment]
Thanks for the report! This should be fixed post 0726a40c2a598c3c7b7f8fa402828cc342ab75b6, please let me know if that doesn't work.
