### ISSUE TITLE
Missing duckling/duckling.cabal on the last commit

### ISSUE THREAD

**Issue by zsellami** [facebook/duckling#189]
I try to build the duckling master project. I got an error message
Warning: The following modules should be added to exposed-modules or other-modules in /data/nlu/duckling/duckling.cabal:
    - In the library component:
        Duckling.AmountOfMoney.EN.US.Rules

Missing modules in the cabal file are likely to cause undefined reference errors from the linker, along with other problems.

--  While building package duckling-0.1.6.0 using:
      /data/nlu/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.2.0 build lib:duckling exe:custom-dimension-example exe:duckling-example-exe exe:duckling-expensive exe:duckling-regen-exe exe:duckling-request-sample --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1

**Comment by patapizza** [comment]
Thanks for reporting @zsellami.

`duckling.cabal` is present but a couple of new files are missing from it in https://github.com/facebook/duckling/commit/f328821bbca9fb4df8e4a5a88a57919a615ffafc. I'm on it.

**Comment by SujaySKumar** [comment]
Still facing this issue with the latest duckling master:

`(.text+0xa1): undefined reference to `ducklingzm0zi1zi6zi1zmFuuoxNkK08bIA0dGJuhBV1_DucklingziNumeralziESziVEziRules_rules_closure'
/home/ubuntu/mozart/duckling/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/libHSduckling-0.1.6.1-FuuoxNkK08bIA0dGJuhBV1.a(ES.o): In function `cF7qi_info'
:
`

```
Warning: The following modules should be added to exposed-modules or other-modules in /home/ubuntu/user/duckling/duckling.cabal:
             - In lib:
                 Duckling.Numeral.ES.AR.Rules
                 Duckling.Numeral.ES.CL.Rules
                 Duckling.Numeral.ES.CO.Rules
                 Duckling.Numeral.ES.ES.Rules
                 Duckling.Numeral.ES.MX.Rules
                 Duckling.Numeral.ES.PE.Rules
                 Duckling.Numeral.ES.VE.Rules
```
