### ISSUE TITLE
How to limit #CPUs used for duckling-example-exe

### ISSUE THREAD

**Issue by resec** [facebook/duckling#193]
I am using duckling to parse time using the duckling-example-exe as a backend server. Currently duckling is using as many CPUs as it can find to work. Can we limit the #CPUs for duckling when we start the server?

Thanks.

**Comment by blandinw** [comment]
Have you tried configuring the Haskell runtime system using (to use 4 OS threads) `stack exec -- duckling-example-exe +RTS -N4 -RTS`?

**Comment by resec** [comment]
@blandinw yes, it worked! GREAT THANKS.
