### ISSUE TITLE
Given weekday with time and duration parsed to a date in year 2030

### ISSUE THREAD

**Issue by akamarukiba** [facebook/duckling#200]
Hi, 

i do not know if you would classify this as a bug, but parsing the text "Wednesday at 2 pm for 30 minutes" results a date in year 2030.

Git: checked out version tag v0.1.6.0
Environment: Docker

Current Date: 28th May 2018 (Monday)

**Query:** 
locale: en_GB
text: Wednesday at 2 pm for 30 minutes

**Expected Result:**
2018-05-30:14:00:00.000

**Result:**
2030-01-02T14:00:00.000

Text used for identification: Wednesday at 2 pm for 30

Output of duckling: 

`[
    {
        "body": "Wednesday at 2 pm for 30",
        "start": 0,
        "value": {
            "values": [
                {
                    "value": "2030-01-02T14:00:00.000-08:00",
                    "grain": "hour",
                    "type": "value"
                },
                {
                    "value": "2030-01-09T14:00:00.000-08:00",
                    "grain": "hour",
                    "type": "value"
                },
                {
                    "value": "2030-01-16T14:00:00.000-08:00",
                    "grain": "hour",
                    "type": "value"
                }
            ],
            "value": "2030-01-02T14:00:00.000-08:00",
            "grain": "hour",
            "type": "value"
        },
        "end": 24,
        "dim": "time",
        "latent": false
    },
    {
        "body": "30 minutes",
        "start": 22,
        "value": {
            "value": 30,
            "type": "value",
            "minute": 30,
            "unit": "minute",
            "normalized": {
                "value": 1800,
                "unit": "second"
            }
        },
        "end": 32,
        "dim": "duration",
        "latent": false
    }
]`

**Comment by haoxuany** [comment]
Yep, that's a bug, thanks for the catch, I'm on it. 😄

**Comment by haoxuany** [comment]
This should now be closed by b64ff2f21b45c644450008d24cb131ab27dd4280. Thanks for the report!
