### ISSUE TITLE
Problem with PCRE after installing Duckling

### ISSUE THREAD

**Issue by AlbertoHdezCerezo** [facebook/duckling#204]
Hi everyone,

Recently I have been trying to install Duckling in an Ubuntu/Xenial 64. Installation did not have any issue, but after running a server instance on my machine, whenever I send a parse request I get an error:

`"POST /parse HTTP/1.1\ncontent-type: application/x-www-form-urlencoded\ncontent-length: 35\naccept: */*\nuser-agent: curl/7.47.0\nhost: localhost:8000\n\nsn=\"localhost:8000\" c=127.0.0.1:53528 s=127.0.0.1:8000 ctx=/ clen=35\nparams: locale: [\"en_GB\"], text: [\"tomorrow at eight\"]"
A web handler threw an exception. Details:
TerminateSessionException user error (Text.Regex.PCRE.String died: (123,"missing terminating ] for character class"))`

Information about my system:

Linux ip-172-31-19-20 4.4.0-1060-aws #69-Ubuntu SMP Sun May 20 13:42:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

PCRE packages installed:

libpcre16-3/xenial,now 2:8.38-3.1 amd64 [installed,automatic]
libpcre3/xenial,now 2:8.38-3.1 amd64 [installed]
libpcre3-dev/xenial,now 2:8.38-3.1 amd64 [installed]
libpcre32-3/xenial,now 2:8.38-3.1 amd64 [installed,automatic]
libpcrecpp0v5/xenial,now 2:8.38-3.1 amd64 [installed,automatic]
pcregrep/xenial,now 2:8.38-3.1 amd64 [installed]

I don't know what is the exact reason if it, maybe something related with PCRE in my system? Need some help with that.

**Comment by haoxuany** [comment]
Hi @AlbertoHdezCerezo, sorry for the late response.

I've tried this on my local machine:
```
curl -XPOST http://localhost:8000/parse --data 'locale=en&text=[\"tomorrow at eight\"]'
```
and received a valid response:
```
[{"body":"tomorrow at eight","start":3,"value":{"values":[{"value":"2018-06-12T08:00:00.000-07:00","grain":"hour","type":"value"},{"value":"2018-06-12T20:00:00.000-07:00","grain":"hour","type":"value"}],"value":"2018-06-12T08:00:00.000-07:00","grain":"hour","type":"value"},"end":20,"dim":"time","latent":false}]
```

You may want to try this, if that doesn't help you, could you post the exact command and request you've sent?

**Comment by AlbertoHdezCerezo** [comment]
Hi @haoxuany , thanks for your help and time :)

I have tried with that exact request on my local machine:

`curl -XPOST http://localhost:8000/parse --data 'locale=en&text=[\"tomorrow at eight\"]'`

The response is always the same:

`curl: (52) Empty reply from server`

When visiting the error log from my local Duckling server, the request has raised this exception:

```[12/Jun/2018:05:51:26 +0000] Exception leaked to httpSession during phase 'user handler':
During processing of request from 127.0.0.1:53832
request:
"POST /parse HTTP/1.1\ncontent-type: application/x-www-form-urlencoded\ncontent-length: 38\naccept: */*\nuser-agent: curl/7.47.0\nhost: localhost:8000\n\nsn=\"localhost:8000\" c=127.0.0.1:53832 s=127.0.0.1:8000 ctx=/ clen=38\nparams: locale: [\"en\"], text: [\"[\\\\\\\"tomorrow at eight\\\\\\\"]\"]"
A web handler threw an exception. Details:
TerminateSessionException user error (Text.Regex.PCRE.String died: (123,"missing terminating ] for character class"))
```

For running the server I also use the command specified in the instructions:

`stack exec duckling-example-exe`

From the Exception registered in the log I suspect there is something wrong with my configuration, but I do follow all the installation steps listed in the instructions, and even tried to reinstall few times the tool. But the problem still persists.

Still don't know what to do

**Comment by haoxuany** [comment]
Sorry, that's my mistake, could you try running this instead?
```
curl -XPOST http://localhost:8000/parse --data 'locale=en_US&text=tomorrow at eight'
```

**Comment by haoxuany** [comment]
Hi @AlbertoHdezCerezo, is this problem resolved?

**Comment by AlbertoHdezCerezo** [comment]
@haoxuany sadly not, I have been trying and looking for other solutions but still the problem persist. I have been checking on a college machine to proceed installing the tool in the same way I do and everything went well there. Maybe is something related to packages/dependencies in my Linux system?

**Comment by haoxuany** [comment]
Hi @AlbertoHdezCerezo, it very well could be. This is likely an issue with linux packages and hackage dependencies. I would recommend removing and upgrading your existing PCRE packages, if that helps. Since this is not a issue directly related to duckling, I'll close this for now, but feel free to reach out (and reopen) if you suspect there's something wrong with duckling configuration.

**Comment by anaswy** [comment]
I am also getting same error:
"POST /parse HTTP/1.1\ncontent-type: application/x-www-form-urlencoded\ncontent-length: 35\naccept: */*\nuser-agent: curl/7.53.1\nhost: 0.0.0.0:8000\n\nsn=\"0.0.0.0:8000\" c=127.0.0.1:36962 s=127.0.0.1:8000 ctx=/ clen=35\nparams: locale: [\"en_GB\"], text: [\"tomorrow at eight\"]"
A web handler threw an exception. Details:
TerminateSessionException user error (Text.Regex.PCRE.String died: (123,"missing terminating ] for character class"))
[11/Jul/2018:07:28:53 +0000] Exception leaked to httpSession during phase 'sending-response': 
During processing of request from 127.0.0.1:36968

Additionally on running "stack test", its telling that:
205 out of 280 tests failed (0.30s)

**Comment by patapizza** [comment]
From a fresh install:

> $ stack build && stack test && stack exec duckling-example-exe
...
All 280 tests passed (3.07s)
duckling-0.1.6.1: Test suite duckling-test passed
Completed 2 action(s).
no port specified, defaulting to port 8000
Listening on http://0.0.0.0:8000

> $ curl -XPOST http://localhost:8000/parse --data 'locale=en_GB&text=tomorrow at eight'
[{"body":"tomorrow at eight","start":0,"value":{"values":[{"value":"2018-07-12T08:00:00.000-07:00","grain":"hour","type":"value"},{"value":"2018-07-12T20:00:00.000-07:00","grain":"hour","type":"value"}],"value":"2018-07-12T08:00:00.000-07:00","grain":"hour","type":"value"},"end":17,"dim":"time","latent":false}]%

So I would try to reinstall the PCRE packages etc.

**Comment by threefoldo** [comment]
Thanks, @turbolent, it solved my problem.

**Comment by day253** [comment]
Thanks, @turbolent , it solved my problem.

**Comment by clobotorre** [comment]
[Dockerfile.txt](https://github.com/facebook/duckling/files/6445554/Dockerfile.txt)
Im running into the same problem, but dont know where to set LANG environment variable. I have a Dockerfile like attached one, where LANG variable is defined as ENV LANG=C.UTF-8 before RUN stack setup, and its defined as ENV LANG C.UTF-8 after RUN stack install.

Im able to run this request succesfully:
curl -XPOST http://localhost:8000/parse --data 'locale=es_ES&text=[\"hoy a las ocho\"]'

But using english locale i run into Empty reply from server

Could you please tell me where I have to set LANG environment variable and what to do then?

**Comment by chessai** [comment]
> 
> [Dockerfile.txt](https://github.com/facebook/duckling/files/6445554/Dockerfile.txt)
> Im running into the same problem, but dont know where to set LANG environment variable. I have a Dockerfile like attached one, where LANG variable is defined as ENV LANG=C.UTF-8 before RUN stack setup, and its defined as ENV LANG C.UTF-8 after RUN stack install.
> 
> Im able to run this request succesfully:
> curl -XPOST http://localhost:8000/parse --data 'locale=es_ES&text=[\"hoy a las ocho\"]'
> 
> But using english locale i run into Empty reply from server
> 
> Could you please tell me where I have to set LANG environment variable and what to do then?
> 

What is the (English locale) request you are sending, and what do you expect as output from it? This sounds like a different issue

**Comment by clobotorre** [comment]
I tried to use the quickstart example:

> curl -XPOST http://0.0.0.0:8000/parse --data 'locale=en_GB&text=tomorrow at eight'

I also tried with sqare brakets and double quotation marks:

> curl -XPOST http://0.0.0.0:8000/parse --data 'locale=en_GB&text=["tomorrow at eight"]'

Output for both these requests is "curl: (52) Empty reply from server"

In duckling log I can see, for first of requets:

```
[09/May/2021:07:34:17 +0000] Exception leaked to httpSession during phase 'user handler': 
During processing of request from 127.0.0.1:46476
request:
"POST /parse HTTP/1.1\ncontent-type: application/x-www-form-urlencoded\ncontent-length: 35\naccept: */*\nuser-agent: curl/7.73.0\nhost: 0.0.0.0:8000\n\nsn=\"0.0.0.0:8000\" c=127.0.0.1:46476 s=127.0.0.1:8000 ctx=/ clen=35\nparams: locale: [\"en_GB\"], text: [\"tomorrow at eight\"]"
A web handler threw an exception. Details:
TerminateSessionException user error (Text.Regex.PCRE.String died: (123,"missing terminating ] for character class"))
```

And for the second request:

```
[09/May/2021:07:37:31 +0000] Exception leaked to httpSession during phase 'sending-response': 
During processing of request from 127.0.0.1:50178
request:
"POST /parse HTTP/1.1\ncontent-type: application/x-www-form-urlencoded\ncontent-length: 39\naccept: */*\nuser-agent: curl/7.73.0\nhost: 0.0.0.0:8000\n\nsn=\"0.0.0.0:8000\" c=127.0.0.1:50178 s=127.0.0.1:8000 ctx=/ clen=39\nparams: locale: [\"en_GB\"], text: [\"[\\\"tomorrow at eight\\\"]\"]"
A web handler threw an exception. Details:
user error (Text.Regex.PCRE.String died: (123,"missing terminating ] for character class"))
```

When I try the spanish version of these requests:

> curl -XPOST http://localhost:8000/parse --data 'locale=es_ES&text=["manana a las ocho"]'

The output is:
```
[{
	"body": "manana a las ocho",
	"start": 2,
	"value": {
		"values": [{
			"value": "2021-05-10T08:00:00.000-07:00",
			"grain": "hour",
			"type": "value"
		}, {
			"value": "2021-05-10T20:00:00.000-07:00",
			"grain": "hour",
			"type": "value"
		}],
		"value": "2021-05-10T08:00:00.000-07:00",
		"grain": "hour",
		"type": "value"
	},
	"end": 19,
	"dim": "time",
	"latent": false
}]
```
And there is no error in log in the Spanish case.

I was expecting a similar output in the English locale case.

As long as the error in log seems to be the same as the issue author posted, I think I'm running in the same issue, but maybe not.

I'm using "Ubuntu 18.04.2 LTS", and I followed instructions from https://github.com/facebook/duckling#quickstart 

>stack build
>stack exec duckling-example-exe

**Comment by chessai** [comment]
Have you tried setting the LANG environment variable before invoking duckling?

Eg `LANG=C.UTF-8 stack exec duckling-example-exe`

**Comment by clobotorre** [comment]
That resolve the problem. Thanks
