### ISSUE TITLE
Duckling not parsing the month of `may`

### ISSUE THREAD

**Issue by LucasLLC** [facebook/duckling#207]
When running `stack exec duckling-example-exe` on master, duckling returns no entities for the following texts:

* `may`
* `What did I do during May?`

**Comment by patapizza** [comment]
Hi @LucasLLC, we stopped parsing `may` by default due to false positives as `may` is pretty common in English: "may I get the menu?".
You can set the latent flag to `true` to get these. We could also parse `during <month>` the same way we do `in <month>` (without the latent flag).

**Comment by LucasLLC** [comment]
That works perfectly! Thanks!

Would parsing `during <month>` be as simple as adding `during` to the regex in this rule?
https://github.com/facebook/duckling/blob/master/Duckling/Time/EN/Rules.hs
Line 106
```
ruleAbsorbInMonthYear :: Rule
ruleAbsorbInMonthYear = Rule
  { name = "in <named-month>|year"
  , pattern =
    [ regex "in"
    , Predicate $ or . sequence [isAMonth, isGrainOfTime TG.Year]
    ]
  , prod = \tokens -> case tokens of
      (_:Token Time td:_) -> tt $ notLatent td
      _ -> Nothing
  }
```

**Comment by patapizza** [comment]
That's right, fancy a pull request? :)

**Comment by LucasLLC** [comment]
Sounds good, let's hope I got this right :)
https://github.com/facebook/duckling/pull/208
