### ISSUE TITLE
Connection refused while trying to make a curl request

### ISSUE THREAD

**Issue by Priprocks** [facebook/duckling#209]
I have made the server up using the dockerfile and its running.
Now when I make a curl request, it shows connection refused.
```
$ curl -XPOST http://0.0.0.0:8000/parse --data 'locale=en_GB&text=tomorrow at eight'
curl: (7) Failed to connect to 0.0.0.0 port 8000: connection refused
```
Also, is there a way to make the server run on localhost instead of 0.0.0.0?

**Comment by patapizza** [comment]
Hi @Priprocks, this is not a Duckling issue.
Are you forwarding the ports from the Docker container to your local machine properly? `localhost` should work too.

**Comment by Priprocks** [comment]
@patapizza yes I'm forwarding the ports properly. Still, the error persists. Also, it isn't working with localhost. I tried so many combinations but it just won't work.
Same connection refused issue pops up.
Is there a way I can configure the IP from 0.0.0.0?

**Comment by justinphan3110** [comment]
have you tried local host ?
