### ISSUE TITLE
A french issue with "du 1er au 15 août"

### ISSUE THREAD

**Issue by HFisselierPro** [facebook/duckling#213]
Hello

We have detected an issue in French when processing kind of sentence "du 1er au 15 aout". It return first day of current month but not first day of august month.

That works in EN with "A bedroom from August 1st to 15th", "A bedroom from  1 to 15 August", ...

How can I solve that issue ?

Regards

**Comment by patapizza** [comment]
Thanks for reporting, I'll look into it.

**Comment by HFisselierPro** [comment]
Thanks @patapizza ! But I've the same issue in English : "from the 22 to the 30th of July". Could you correct this too ?
