### ISSUE TITLE
'Branch' is always seen as a date, even when not applicable

### ISSUE THREAD

**Issue by stefanievonk** [facebook/duckling#215]
When using the word 'branch' in a text and using the en_GB duckling, the result always shows a date, even when this is not meant at all.. Is this something we can avoid?

![image](https://user-images.githubusercontent.com/38073972/41965759-a2b20152-79fd-11e8-829e-8c7a6fcbd4d2.png)

**Comment by patapizza** [comment]
Thanks for reporting! Fix coming up.
