### ISSUE TITLE
Duration not recognized when number is written twice

### ISSUE THREAD

**Issue by stefanievonk** [facebook/duckling#216]
When the duration includes two ways of writing the number, the duration is not recognized anymore. Is this something that can be fixed?

**curl -XPOST http://0.0.0.0:8000/parse --data 'locale=en_GB&text=twelve (12) years'**
[{"body":"twelve","start":0,"value":{"value":12,"type":"value"},"end":6,"dim":"number","latent":false},{"body":"12","start":8,"value":{"value":12,"type":"value"},"end":10,"dim":"number","latent":false}]

**Comment by patapizza** [comment]
Hi @stefanievonk, can you provide a little more context? This doesn't seem common.

**Comment by stefanievonk** [comment]
We see this mostly when analyzing contract data. The number is then fully written out and shown in numbers. Combinations that might occur:
Three (3) days
3 (three) day
3 , three , days
etc.

As seen in the output, the individual numbers are recognized, but the duration not anymore. Is this enough context or do you need more information?

**Comment by patapizza** [comment]
Thank you. Can you try to give it a shot and submit a pull request? :)

**Comment by stefanievonk** [comment]
Unfortunetly, I have never used Haskell, but what I would think could be a solution, is include it as new parts of the corpus as shown below. Do you think that will work?

`
allExamples :: [Example]
allExamples = concat
  [ examples (DurationData 1 Second)
             [ "one sec"
             , "1 second"
             , "1\""
             ]
  , examples (DurationData 2 Minute)
             [ "2 mins"
             , "two minutes"
             , "2'"
             ]
  , examples (DurationData 30 Day)
             [ "30 days"
             ]
  , examples (DurationData 7 Week)
             [ "seven weeks"
             ]
  , examples (DurationData 1 Month)
             [ "1 month"
             , "1 (one) month"
             , "one (1) month"
             , "a month"
             ]
  , examples (DurationData 3 Quarter)
             [ "3 quarters"
             ]
  , examples (DurationData 2 Year)
             [ "2 years"
             , "two years"
             , "2 (two) years"
             , "two (2) years"
             ]
  , examples (DurationData 30 Minute)
             [ "half an hour"
             , "half hour"
             , "1/2 hour"
             , "1/2h"
             , "1/2 h"
             ]
  , examples (DurationData 12 Hour)
             [ "half a day"
             , "half day"
             , "1/2 day"
             ]
  , examples (DurationData 90 Minute)
             [ "an hour and a half"
             , "one hour and half"
             ]
  , examples (DurationData 45 Day)
             [ "a month and a half"
             , "one month and half"
             ]
  , examples (DurationData 27 Month)
             [ "2 years and 3 months"
             , "2 (two) years and 3 (three) months"
             , "two (2) years and three (3) months"
             , "2 years, 3 months"
             , "2 (two) years, 3 (three) months"
             , "two (2) years, three (3) months"
             ]
  , examples (DurationData 31719604 Second)
             [ "1 year, 2 days, 3 hours and 4 seconds"
             , "1 year 2 days 3 hours and 4 seconds"
             ]
  ]`

**Comment by patapizza** [comment]
Reference: https://github.com/facebook/duckling#extending-duckling
Corpus examples act as unit tests, so this would be the ideal start. With this change, running the test suite would show that these examples fail.
Next you'll need to implement the actual change in the `Rules.hs` file (I'm thinking adding a new rule taking a `Numeral`, the character '(', another `Numeral`, the character ')' and a `TimeGrain` would do it).

**Comment by stefanievonk** [comment]
I looked into the rules section, but cannot really figure out what the individual parts mean. I think the name is something like the description of the rule, but how the _pattern_ and _prod_ should be implemented is a bit harder. 

```
ruleDurationNumeralGrain :: Rule
ruleDurationNumeralGrain = Rule
  { name = "<integer> + '(' <integer> + ')' + <unit-of-duration>"
  , pattern =
    [ Predicate isNatural
    , dimension TimeGrain
    ]
  , prod = \case
      (Token Numeral nd:_:Token TimeGrain grain:_) ->
        Just . Token Duration . duration grain . floor $ TNumeral.value nd
      _ -> Nothing
  }
```

**Comment by patapizza** [comment]
From the README:
> Rules have a name, a pattern and a production. Patterns are used to perform character-level matching (regexes on input) and concept-level matching (predicates on tokens). Productions are arbitrary functions that take a list of tokens and return a new token.

In this case, the pattern will match a `Numeral` token that is a natural number followed by a `TimeGrain` token. By rule composition, the first pattern item will match any natural number (e.g. "one", "1", "three", "3") followed by any time grain (e.g. "year", "months").
The production will take these 2 tokens and create a new token `Duration`.

I described above how "1 (one) year" could be implemented by a new `Duration` rule.

Hope this helps.
