### ISSUE TITLE
Wrong start date with "from the 22 to the 30th of July"

### ISSUE THREAD

**Issue by HFisselierPro** [facebook/duckling#218]
Hello

With "from the 22 to the 30th of July", the start date is not well recognized. It respond 2018-06-29 and not the right value 2018-07-22.

Could you correct that ?

**Comment by xhavokx** [comment]
Hi @HFisselierPro ,

Thanks for reporting this. Are you able to give it a shot and submit a pull request? :-)

**Comment by MorrisLaw** [comment]
Hey @xhavokx I'll give it a shot. I'll make a PR soon.  May have some questions along the way though.

**Comment by MorrisLaw** [comment]
Good morning, from the East Coast, @xhavokx  and @patapizza! Are there any existing tests for this part of the code? Also, which section is this handled exactly? Thank you!

**Comment by patapizza** [comment]
Hi @MorrisLaw!
All corpus examples work as unit tests. So you can add a few more [here](https://github.com/facebook/duckling/blob/master/Duckling/Time/EN/Corpus.hs#L952). Note that the reference time for the tests is [Tuesday Feb 12, 2013 at 4:30am](https://github.com/facebook/duckling/blob/master/Duckling/Testing/Types.hs#L76).

**Comment by MorrisLaw** [comment]
Hey @patapizza when you get a chance please review. I am stuck on adding a regex for a test case.

**Comment by patapizza** [comment]
Sorry for the latency @MorrisLaw. Just reviewed the PR!

**Comment by MorrisLaw** [comment]
Np @patapizza thank you!
