### ISSUE TITLE
Get the date and time wrong. 

### ISSUE THREAD

**Issue by quocthinh212** [facebook/duckling#225]
https://github.com/facebook/duckling/blob/e279c5642e823a3a11f63e7982cb07d5e32f7f91/Duckling/Time/VI/Rules.hs#L307

Regex rule for get month is wrong for VI datetime,

Error occurs when month is 10 11 12,

(12/12) ->  result is:    day:12 and month: 1 .  

Please change it to: 

`(3[01]|[12]\d|0?[1-9])[/-](1[0-2]|0?[1-9])`

 https://github.com/facebook/duckling/blob/e279c5642e823a3a11f63e7982cb07d5e32f7f91/Duckling/Time/VI/Rules.hs#L175
and 
https://github.com/facebook/duckling/blob/e279c5642e823a3a11f63e7982cb07d5e32f7f91/Duckling/Time/VI/Rules.hs#L867

**Comment by xhavokx** [comment]
HI @quocthinh212, 

Thanks for finding this issue. Do you think you could take a shot at making the change and submitting a PR?

Thanks

**Comment by xtianjohns** [comment]
Hey @quocthinh212 I have a change reversing the matches, but I'm not actually experiencing bad behavior with this regex, can you give me a reproducible example? What I've used that matches correctly:

```
ngày 12/10
ngày 12/12
ngày 12/12/2018
ngày 12/10/2000
```
Each are giving me the correct month and day identifiers, without the improper matching. Reversing the expressions on either side of the `or` for month still does this, and the tests still pass, but I can't verify the bad behavior to write a new test.

**Comment by quocthinh212** [comment]
Hi @xtianjohns . i only test with this regex on my code and it work not exactly.
My screenshoot: 
![screenshots](https://user-images.githubusercontent.com/14103334/42988659-ae88fb66-8c27-11e8-9056-45cbd69e36ab.png)

After i change regex 
![screenshosat](https://user-images.githubusercontent.com/14103334/42988712-d5a5da2a-8c27-11e8-99ef-3d0a579e1b22.png)

**Comment by xtianjohns** [comment]
Yep yep, I'm seeing this too now, the result from 12-25. I think what's happening in your pasted snippet from Wit is that we're matching on the wrong rule (when I debug, I see the rule for giáng sinh, not ngày mm/dd).

You're definitely right about the PCRE regex, I'm so used to seeing POSIX that I'd forgotten it will greedy match. `a|b` is not the same as `b|a`.

I'm working on a PR, it'll be up in a bit. Thanks @quocthinh212!

**Comment by quocthinh212** [comment]
I think this regex is not true:
https://github.com/facebook/duckling/blob/e279c5642e823a3a11f63e7982cb07d5e32f7f91/Duckling/Time/VI/Rules.hs#L930

**Comment by xtianjohns** [comment]
Yep! It matched on 0, while the other rules didn't catch it. When I reverse the order of the captures on either side of the pipe, I get the correct behavior.
