### ISSUE TITLE
calling from c/c++

### ISSUE THREAD

**Issue by cogmeta** [facebook/duckling#235]
Has anyone tried calling it form c/c++ code?

**Comment by adanielescu** [comment]
Hi there, 
Are you running into problems calling the code from C? There's information on how to call Haskell code from C on the haskel.org website here: https://wiki.haskell.org/Calling_Haskell_from_C

Here's also an open source example that I found: https://github.com/jarrett/cpphs

Feel free to reach out again if you have specific questions with details. 

Thanks!
