### ISSUE TITLE
Stopping duckling server gracefully

### ISSUE THREAD

**Issue by Krogsager** [facebook/duckling#237]
I'm using duckling to extract datetime from chat messages in [rasa](https://github.com/RasaHQ/rasa_core).
I don't know haskell and I rely on the quickstart code to use duckling, so I simply run the command
`stack exec duckling-example-exe`

If I stop the process I cannot start it again (without restarting my computer). I get the message:
```
andkr@Anderss-MacBook-Pro.local:~/rasa/duckling$stack exec duckling-example-exe
no port specified, defaulting to port 8000
duckling-example-exe: Network.Socket.bind: resource busy (Address already in use)
```

How do I gracefully stop the service?  Ctrl+C does not cut it.

**Comment by chessai** [comment]
Did you resolve this?

Also, on linux (not sure if MacOS as well, but probably), if a socket is not opened with the SO_REUSEADDR flag set, then you must wait for the operating system to actually free up the file descriptor backing the socket. In my experience this can take 30-60 seconds even after killing the relevant process.
