### ISSUE TITLE
Installing on Windows 10

### ISSUE THREAD

**Issue by neel17** [facebook/duckling#238]
Hi,
I have been trying to install on Windows but could not install. Raised a question on stackoverflow as well but no help [stackoverflow question link](https://stackoverflow.com/questions/51871998/duckling-installation-on-windows-missing-c-library-pcre-on-windows) 

It is always asking me for pcre related issue. I am using stack for the installation. 

Kindly help!!! Really stuck at this point!!!

Thanks,

Neel

**Comment by adanielescu** [comment]
HI, 
1. Have you tried installing PCRE on windows? More info about installing on windows can be installed here: https://www.pcre.org/ I know this is required on mac.
2. If you have and you're still running into problems, can you please copy the exact error you're getting? 

Thanks.

**Comment by neel17** [comment]
PCRE installation itself is proving to be a big task for me on windows. I have tried it and in my [stackoverflow question](https://stackoverflow.com/questions/51871998/duckling-installation-on-windows-missing-c-library-pcre-on-windows) I have shared the screenshots as well. 

LIke Mac : `brew install pcre` unfortunately we don't have anything for windows. 

I have now moved to Ubuntu instance!!

Thanks anyways!

**Comment by sp3tsnaz** [comment]
> I have changed "regex-pcre" in duckling.cabal to "regex-pcre-builtin" (The PCRE backend to accompany regex-base, with bundled code from [www.pcre.org](http://www.pcre.org))
> http://hackage.haskell.org/package/regex-pcre-builtin
> 
> ... and this compiled correctly

Thanks (Y). Worked for me too!!
