### ISSUE TITLE
Automatic Docker image on Docker hub

### ISSUE THREAD

**Issue by tijsg** [facebook/duckling#241]
On hub.docker.com you can create an automated Docker image from the Dockerfile that you already have in this repo. Would be nice if you could add it, so others don't have to build it themselves.

**Comment by faheem-cliqz** [comment]
Guys any plans for this? It should be rather simple to do this.

**Comment by Raphencoder** [comment]
Hi guys !
I did it if someone is interested. 
Available on DockerHub
You just need to pull the image.
Here the address:
https://cloud.docker.com/repository/docker/raphsopi/duckling/general

**Comment by chessai** [comment]
Thanks for the issue. See #544
