### ISSUE TITLE
Changing the definition of "weekend"

### ISSUE THREAD

**Issue by figelwump** [facebook/duckling#242]
I'm attempting to modify the definition of what "weekend" means in my fork of duckling. (For my purposes, I'm changing it to be Sat -> Sun instead of Fri evening -> Sun). I've modified the `weekend` function in Helpers.hs like so:

```
weekend :: TimeData
weekend = interval' TTime.Open (sat, sun)
  where
    sat = intersect' (dayOfWeek 6, hour False 0)
    sun = intersect' (dayOfWeek 0, hour False 0)
```

And modified the weekend-related samples in Time/EN/Corpus.hs

And rebuilt it with:
` stack build :duckling-regen-exe && stack exec duckling-regen-exe`

But when I run `stack exec duckling-example-exe` and test with: `locale=en_US&text=this weekend` I still get the old definition of weekend.

I'm new to duckling, and new to haskell, so it's certainly something I'm missing. Any guidance here would be appreciated!

**Comment by figelwump** [comment]
Thanks that worked! Can you help me understand what the difference is between those build commands and the ones I ran?

Also, for tests -- I've changed the corpus samples in `Time/EN/Corpus.hs`, is this sufficient? I'm not sure I understand what exactly is being tested and how tests work.

**Comment by figelwump** [comment]
Thanks, this is really helpful.

So to clarify -- for the Time dimension, English language, the samples in `Time/EN/Corpus.hs` are used for both training the classifiers and for tests?

**Comment by patapizza** [comment]
Yes that's correct: corpus examples are both used as unit tests and as training data for the classifiers.
