### ISSUE TITLE
next week is parsed as one date but next 2 weeks as a range

### ISSUE THREAD

**Issue by timaschew** [facebook/duckling#246]
Tested on 
https://duckling.wit.ai/#contributing

I would expect to see a range for `next week` as well.

**Comment by haoxuany** [comment]
Hi @timaschew, thanks for the report. For dimension Time, it depends on context. It is generally more common to use "next week" in the context of referring to the date of next week, and "next 2 weeks" in the context of referring to the date range between in two weeks. If you want the interval of dates for a wekk, use "in 1 week" or "in a week" instead.

Please let me know if this makes sense.

**Comment by timaschew** [comment]
Hi @haoxuany thanks for the fast response.

What you said makes sense, but the parser output is still a bit confusing.

**next weekend** is a `<time>`
Output:
> From Friday, 31 August 2018 at 18:00:00 -0700 (-07:00) 
to Monday, 3 September 2018 at 0:00:00 -0700 (-07:00) :hour

**next week** is a `<cycle>`
Output:
>Monday, 27 August 2018 :week

**in a week/in 1 week** is a `<duration>`
Output:
>Saturday, 1 September 2018 :day

What I would like to see, how do I get this output?

> From Monday, 27 August 2018 at 00:00:00 -0700 (-07:00) 
to Sunday, 2 September 2018 at 00:00:00 -0700 (-07:00) 

---

Found one, it's **from monday to sunday** which is an interval with two `<datetime>` elements.

I guess there is no way to get that with just the word `week`?

**Comment by patapizza** [comment]
HI @timaschew, https://duckling.wit.ai still runs the legacy Clojure code. Use the example server shown in the README to test the latest library:

```
$ curl -XPOST http://localhost:8000/parse --data 'locale=en_XX&text=next week'
[{"body":"next week","start":0,"value":{"values":[{"value":"2018-08-27T00:00:00.000-07:00","grain":"week","type":"value"}],"value":"2018-08-27T00:00:00.000-07:00","grain":"week","type":"value"},"end":9,"dim":"time","latent":false}]

$ curl -XPOST http://localhost:8000/parse --data 'locale=en_XX&text=next 2 weeks'
[{"body":"next 2 weeks","start":0,"value":{"values":[{"to":{"value":"2018-09-10T00:00:00.000-07:00","grain":"week"},"from":{"value":"2018-08-27T00:00:00.000-07:00","grain":"week"},"type":"interval"}],"to":{"value":"2018-09-10T00:00:00.000-07:00","grain":"week"},"from":{"value":"2018-08-27T00:00:00.000-07:00","grain":"week"},"type":"interval"},"end":12,"dim":"time","latent":false}]%

$ curl -XPOST http://localhost:8000/parse --data 'locale=en_XX&text=next weekend'
[{"body":"next weekend","start":0,"value":{"values":[{"to":{"value":"2018-08-27T00:00:00.000-07:00","grain":"hour"},"from":{"value":"2018-08-24T18:00:00.000-07:00","grain":"hour"},"type":"interval"}],"to":{"value":"2018-08-27T00:00:00.000-07:00","grain":"hour"},"from":{"value":"2018-08-24T18:00:00.000-07:00","grain":"hour"},"type":"interval"},"end":12,"dim":"time","latent":false}]
```

Weekends are arbitrarily defined from Friday 6pm to Monday midnight, exclusive. You'll need to wait for https://github.com/facebook/duckling/issues/29 to override this, to ensure backward compatibility.

As the grain for `next week` is a `week`, you can compute the outer interval bound from the given timestamp, and effectively convert it to a day range. Hope this helps.
