### ISSUE TITLE
Execute expensive script

### ISSUE THREAD

**Issue by shakimov** [facebook/duckling#248]
Hi all,

I was wondering how to  [Duckling-Expensive](https://github.com/facebook/duckling/blob/master/exe/DucklingExpensive.hs)  ?

I needs some sort of JSON file I guess that is parsed and the server starts ...

Thanks for any help.

**Comment by beauby** [comment]
Hey, could you be more specific about what you are trying to achieve, and what is your current setup?

**Comment by shakimov** [comment]
There are 3 executable Haskell programs that are built after compiling the project.
I'd like to run the **expensive** one, which requires some sort of JSON file as an input in order to run.

The executable **duckling-example-exe** runs without any input file.

Is there an example file that i could use ?

Regards,

**Comment by blandinw** [comment]
@shakimov The [`expensive`](https://github.com/facebook/duckling/blob/master/exe/DucklingExpensive.hs) executable does not support reading input from JSON/stdin. You have to edit the source code yourself at the moment, [in this file](https://github.com/facebook/duckling/blob/master/exe/DucklingExpensive.hs).

You can then run it and specify the number of times you want to run (e.g. 1337 times) like so `stack exec duckling-expensive 42`.

Closing now, but please comment back if something's not clear.
