### ISSUE TITLE
locale not working on oxs?

### ISSUE THREAD

**Issue by sangszhou** [facebook/duckling#252]
I tried different locale as parameter to duckling server but it returns same result. Wonder if it's because of the OS.

**Comment by beauby** [comment]
Hi @sangszhou – how exactly did you provide the locale? Also, are you using [exe/ExampleMain.hs](https://github.com/facebook/duckling/blob/master/exe/ExampleMain.hs) or some custom setup?

**Comment by sangszhou** [comment]
I didn't do any customization, just compile and run the code as readme.md described. 

I change the locale parameter to zh_CN for this command  `$ curl -XPOST http://0.0.0.0:8000/parse --data 'locale=en_GB&text=tomorrow at eight' but the result is same with en_GB's. Tried several other locales but the result is still the same.

**Comment by patapizza** [comment]
Can you give the exact command you're using?

**Comment by sangszhou** [comment]
`curl -XPOST http://0.0.0.0:8000/parse --data 'locale=zh_CN&text=8 am`

`
{
  "body": "8 am",
  "start": 0,
  "value": {
    "values": [
      {
        "value": "2018-09-07T08:00:00.000-07:00",
        "grain": "hour",
        "type": "value"
      },
      {
        "value": "2018-09-08T08:00:00.000-07:00",
        "grain": "hour",
        "type": "value"
      },
      {
        "value": "2018-09-09T08:00:00.000-07:00",
        "grain": "hour",
        "type": "value"
      }
    ],
    "value": "2018-09-07T08:00:00.000-07:00",
    "grain": "hour",
    "type": "value"
  },
  "end": 4,
  "dim": "time",
  "latent": false
}
`

it give me the correct result now, because it's pretty late today(11:29pm). I will run it again after 31 minutes.

**Comment by sangszhou** [comment]
besides the 8th line (RUN stack build) of dockerfile installation throws an exception 

```
Step 8/9 : RUN stack build
 ---> Running in 6e139c1985bb

Updating package index Hackage (mirrored at https://s3.amazonaws.com/hackage.fpcomplete.com/) ...
Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/
Downloading root
Unable to load cabal files for snapshot

----
Deleting cached snapshot file: /root/.stack/build-plan/lts-9.10.yaml
Recommendation: try running again. If this fails again, open an upstream issue at:
https://github.com/fpco/lts-haskell/issues/new
```

it's very strange because I got VPN running on my laptop, networking should not be a problem. But I'm not familiar with haskel tech stacks, so cannot figure out why.

**Comment by patapizza** [comment]
@sangszhou: It does return the correct resolution for the `America/Los_Angeles` timezone (it's still Friday, September 7 there). Can you try providing the timezone using the `tz` parameter?

Not sure about Docker, I would follow the recommendation from the output.

**Comment by chessai** [comment]
@sangszhou like @patapizza mentions, you need to set the correct timezone. by default it is America/Los_Angeles. Duckling makes no attempt to determine the timezone of where it is running/the local system.
