### ISSUE TITLE
Icelandic language added but one Test failing

### ISSUE THREAD

**Issue by kumar-shridhar** [facebook/duckling#253]
My test is failing and in the CI Pipeline, I see this error:
IS Tests
        Corpus Tests:              FAIL (0.32s)
          tests/Duckling/Testing/Asserts.hs:84:
          empty result on "n\250ll"

I checked the "Assert.hs" file under IS and everything looks alright. I donot know why this is failing. Any clues, anyone ?

**Comment by patapizza** [comment]
The main issue was that the `Duckling/Rules.hs` file was not edited properly.
Closing in favor of https://github.com/facebook/duckling/pull/247.
