### ISSUE TITLE
Handling "in the" before "next few <duration>"

### ISSUE THREAD

**Issue by figelwump** [facebook/duckling#254]
Currently, duckling correctly parses a phrase like "next few days". If you say something like "in the next few days", the "in the" phrase is ignored and not returned in the `body` parameter.

For my purpose, however, I would like "in the" returned in the `body`, because I'm using that to extract out all the time-related text from the original phrase.

To do this, I made the following attempt at modifying `Time/EN/Rules.hs`:

```
ruleDurationLastNext = Rule
  { name = "[in the] last|past|next <duration>"
  , pattern =
    [ regex "(in)?\\s*(the)?\\s*"
    , regex "([lp]ast|next)"
    , dimension Duration
    ]
  , prod = \tokens -> case tokens of
      (_:
       Token RegexMatch (GroupMatch (match:_)):
       Token Duration DurationData{TDuration.grain, TDuration.value}:
       _) -> case Text.toLower match of
         "next" -> tt $ cycleN True grain value
         "last" -> tt $ cycleN True grain (- value)
         "past" -> tt $ cycleN True grain (- value)
         _      -> Nothing
      _ -> Nothing
  }
```

I've also modified the corresponding English corpus examples.

However, when I build and run this, "in the next few days" now parses as a Duration dimension instead of Time, giving incorrect results.

Any pointers? How can I debug what's going wrong here?

**Comment by patapizza** [comment]
Hi @figelwump,

You can use the helpers from `Duckling.Debug` to see the parse trees (example usage at the bottom of the `README`). I expect another rule to kick in. To go around that, add a few corpus examples and regenerate the classifiers before running the test suite.

Hope this helps.

**Comment by figelwump** [comment]
Thanks, this is helpful. I've added corpus examples to `Time/EN/Corpus`. I still have an issue when testing just the phrase "in the next few days" vs. something like "make coffee in the next few days". The latter case still gives me the wrong dimension (Duration instead of Time).

Debug info:

```
*Duckling.Debug> debug (makeLocale EN $ Just US) "in the next few days" []
[in the] last|past|next <duration> (in the next few days)
-- regex (in the )
-- regex (next)
-- <integer> <unit-of-duration> (few days)
-- -- integer (0..19) (few)
-- -- -- regex (few)
-- -- day (grain) (days)
-- -- -- regex (days)
[Entity {dim = "time", body = "in the next few days", value = RVal Time (TimeValue (IntervalValue (InstantValue {vValue = 2013-02-13 00:00:00 -0200, vGrain = Day},InstantValue {vValue = 2013-02-16 00:00:00 -0200, vGrain = Day})) [IntervalValue (InstantValue {vValue = 2013-02-13 00:00:00 -0200, vGrain = Day},InstantValue {vValue = 2013-02-16 00:00:00 -0200, vGrain = Day})] Nothing), start = 0, end = 20, latent = False, enode = Node {nodeRange = Range 0 20, token = Token Time TimeData{latent=False, grain=Day, form=Nothing, direction=Nothing, holiday=Nothing, hasTimezone=False}, children = [Node {nodeRange = Range 0 7, token = Token RegexMatch (GroupMatch ["in","the"]), children = [], rule = Nothing},Node {nodeRange = Range 7 11, token = Token RegexMatch (GroupMatch ["next"]), children = [], rule = Nothing},Node {nodeRange = Range 12 20, token = Token Duration (DurationData {value = 3, grain = Day}), children = [Node {nodeRange = Range 12 15, token = Token Numeral (NumeralData {value = 3.0, grain = Nothing, multipliable = False, okForAnyTime = False}), children = [Node {nodeRange = Range 12 15, token = Token RegexMatch (GroupMatch ["few","","","",""]), children = [], rule = Nothing}], rule = Just "integer (0..19)"},Node {nodeRange = Range 16 20, token = Token TimeGrain Day, children = [Node {nodeRange = Range 16 20, token = Token RegexMatch (GroupMatch []), children = [], rule = Nothing}], rule = Just "day (grain)"}], rule = Just "<integer> <unit-of-duration>"}], rule = Just "[in the] last|past|next <duration>"}}]
```

```
*Duckling.Debug> debug (makeLocale EN $ Just US) "make coffee in the next few days" []
<integer> <unit-of-duration> (few days)
-- integer (0..19) (few)
-- -- regex (few)
-- day (grain) (days)
-- -- regex (days)
[Entity {dim = "duration", body = "few days", value = RVal Duration (DurationData {value = 3, grain = Day}), start = 24, end = 32, latent = False, enode = Node {nodeRange = Range 24 32, token = Token Duration (DurationData {value = 3, grain = Day}), children = [Node {nodeRange = Range 24 27, token = Token Numeral (NumeralData {value = 3.0, grain = Nothing, multipliable = False, okForAnyTime = False}), children = [Node {nodeRange = Range 24 27, token = Token RegexMatch (GroupMatch ["few","","","",""]), children = [], rule = Nothing}], rule = Just "integer (0..19)"},Node {nodeRange = Range 28 32, token = Token TimeGrain Day, children = [Node {nodeRange = Range 28 32, token = Token RegexMatch (GroupMatch []), children = [], rule = Nothing}], rule = Just "day (grain)"}], rule = Just "<integer> <unit-of-duration>"}}]
```

Do I need more corpus examples; if so, which ones? How do I read this debug data to figure out why one phrase is being interpreted differently than the other?

**Comment by patapizza** [comment]
Making them non-optional work: `regex "in\\s*the\\s*"`. The engine takes care of the blank characters between pattern items, so we can drop the last `\\s*`, and to prevent `inthe`, let's do `\\s+` for the first one.

A better solution would be to merge both regex patterns into a single one: `regex "(in\\s+the\\s+)?([lp]ast|next)"` (you'd need to do `GroupMatch (_:match:_)` to capture the second group in the production).

Corpus examples help to disambiguate multiple valid parse trees, and expect the full text to be matched (that is, without `make coffee `).
`debug` shows you the returned entities along with the matched text and the underlying parse tree. In the second case, it only captured `few days` (not even `next`) which means there was an issue with the `ruleDurationLastNext`.
