### ISSUE TITLE
Exclude language from common rules 

### ISSUE THREAD

**Issue by dallal9** [facebook/duckling#255]
I'm working on adding a dialect as a new language on duckling and i do want the Numeral common rules to be applied to the language. is there a way to do so?

**Comment by patapizza** [comment]
Just to clarify, do you want or not want the common rules? What dialect is it?

**Comment by dallal9** [comment]
i changed the Duckling/Rules.hs adding this (where LTDA is the language i'm trying to exclude it from some of the general rules) 
`rulesFor' :: Locale -> Some Dimension -> [Rule]
rulesFor' (Locale lang (Just region)) dim =
  if lang == LTDA then CommonRules.somerules dim ++ langRules lang dim ++ localeRules lang region dim
  else CommonRules.rules dim ++ langRules lang dim ++ localeRules lang region dim
rulesFor' (Locale lang Nothing) dim =
  if lang == LTDA then CommonRules.somerules dim ++ defaultRules lang dim
  else CommonRules.rules dim ++ defaultRules lang dim`
and i changed Duckling/Rules/Common.hs  adding new set of rules

**Comment by patapizza** [comment]
Just curious, what is LTDA? If it's not meant for commit, then some hack like above works. To keep things simpler though it's usually best to just duplicate the rules you don't want to see in a specific language within all other languages rules, and remove it from the common rules.

Hope this helps.

**Comment by dallal9** [comment]
I'm working on and Arabic dialect (Moroccan Arabic )
the thing is it's more easier to have some common rule. it's only the numbers that made problem because in this case numbers are used as letters. 
the commit i want to work on this related to arabic in general, is this issue https://github.com/facebook/duckling/issues/131 , i have a solution and i tested it but there are some specialcase i need to work on
