### ISSUE TITLE
Timezone offset

### ISSUE THREAD

**Issue by mbektimirov** [facebook/duckling#259]
Is there any possible way to detect timezone offset like `10:00 GMT+5`, `7 pm UTC-3`?

**Comment by blandinw** [comment]
Hi @mbektimirov, it looks like our current English timezone parsing rules do not support offsets (`+5`, `-3`). [The rules are here](https://github.com/facebook/duckling/blob/master/Duckling/Time/EN/Rules.hs#L2278) if you'd like to contribute!
