### ISSUE TITLE
url request with timezone argument

### ISSUE THREAD

**Issue by chiapas** [facebook/duckling#261]
After reading [this post](https://github.com/facebook/duckling/issues/87), I still don't know how to specify the timezone in the request provided in README.md

curl -XPOST http://0.0.0.0:8000/parse --data 'locale=en_GB&text=tomorrow at eight'

It seems by default, it works with UTC-7. And for example, if I want to work with UTC+2, what is the argument name and the format of argument value I should provide.

More generally, where I can find the list of available arguments.

Please help me. I feel lost...

**Comment by patapizza** [comment]
@chiapas: The [tz](https://github.com/facebook/duckling/blob/master/exe/ExampleMain.hs#L79) parameter defines the timezone. This parameter reads the [Olson data](https://github.com/facebook/duckling/blob/master/exe/Duckling/Data/TimeZone.hs#L34); it handles things like `Europe/Brussels`, `America/Los_Angeles` ([default](https://github.com/facebook/duckling/blob/f8c967c28df0fbdf3fc2726afdc8fa20f3ad2bad/exe/ExampleMain.hs#L107)).
Hope this helps.
