### ISSUE TITLE
Deploying Duckling on AWS Ec2 or Heroku to use as an active service 

### ISSUE THREAD

**Issue by balaram-bhukya** [facebook/duckling#263]
I am trying to deploy Duckling on AWS or Heroku . I failed to deploy on heroku becoz the file size exceeds 1 GB . How can I use this as a active service for my application form EC2

**Comment by patapizza** [comment]
Hi @balaram-bhukya,
What file is exceeding 1GB? The server example binary is 38M on my laptop.
Here's a project that can help in getting Haskell code on Heroku: https://github.com/mfine/heroku-buildpack-stack.
