### ISSUE TITLE
Empty reply from server when using long text

### ISSUE THREAD

**Issue by stefanievonk** [facebook/duckling#283]
When trying to parse a long set of dates in one string, an empty reply from the server is given. 
`
curl -XPOST http://0.0.0.0:8000/parse --data 'locale=pt_XX&text=01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16 01/06/16'      
curl: (52) Empty reply from server   
`

Using the same date, but less often, does give a response:
`curl -XPOST http://0.0.0.0:8000/parse --data 'locale=pt_XX&text=01/06/16 01/06/16 01/06/16 01/06/16'
[{"body":"01/06/16 01/06/16 01/06/16 01/06/16","start":0,"value":{"values":[{"value":"2016-06-01T00:00:00.000-07:00","grain":"day","type":"value"}],"value":"2016-06-01T00:00:00.000-07:00","grain":"day","type":"value"},"end":35,"dim":"time","latent":false}]`

**Comment by patapizza** [comment]
Hi @stefanievonk,

I expect this to take a very long time to parse and resolve.
The empty reply is probably due to a default timeout in `curl`: https://unix.stackexchange.com/questions/94604/does-curl-have-a-timeout/94612.
