### ISSUE TITLE
Question on pattern matching rule

### ISSUE THREAD

**Issue by vijay120** [facebook/duckling#286]
I have pasted code below for a particular rule:

```haskell
ruleNumeralAsTemp :: Rule
ruleNumeralAsTemp = Rule
  { name = "number as temp"
  , pattern =
    [ dimension Numeral
    ]
  , prod = \tokens -> case tokens of
      (Token Numeral nd:_) ->
        Just . Token Temperature $ valueOnly $ floor $ TNumeral.value nd
      _ -> Nothing
  }
```

What does `dimension Numeral` mean in the pattern clause? Does it mean it will match **any** numerals in a string (it does not do this right now)? What does it mean to match on a dimension?

**Comment by patapizza** [comment]
`dimension` is defined [here](https://github.com/facebook/duckling/blob/master/Duckling/Types.hs#L316-L317).

Yes, it will match any tokens of dimension `Numeral`, which means any string matches currently supported by `Numeral`. Which specific example doesn't work?

**Comment by vijay120** [comment]
@patapizza  Thanks for helping! Here are some examples I do not understand:

**Preconditions**:
```
*Duckling.Debug> testContext
Context {referenceTime = DucklingTime 2013-02-12 02:30:00 -0200, locale = EN_XX}

*Duckling.Debug> testOptions
Options {withLatent = False}
```


**Query**: `ok 2.0 is my number`
**Input**: `parse "ok 2.0 is my number" testContext testOptions []`
**Output**: 
`[Entity {dim = "number", body = "2.0", value = RVal Numeral (NumeralValue {vValue = 2.0}), start = 3, end = 6, latent = False, enode = Node {nodeRange = Range 3 6, token = Token Numeral (NumeralData {value = 2.0, grain = Nothing, multipliable = False, okForAnyTime = True}), children = [Node {nodeRange = Range 3 6, token = Token RegexMatch (GroupMatch ["2.0"]), children = [], rule = Nothing}], rule = Just "decimal number"}}]`

**Understanding**: Duckling correctly parsed `2.0` as a Numeral entity since it matches this rule:

```haskell
ruleDecimals :: Rule
ruleDecimals = Rule
  { name = "decimal number"
  , pattern =
    [ regex "(\\d*\\.\\d+)"
    ]
  , prod = \tokens -> case tokens of
      (Token RegexMatch (GroupMatch (match:_)):_) -> parseDecimal True match
      _ -> Nothing
  }
```

**Query**: `ok by 2.0 is my number`
**Input**: `parse "ok by 2.0 is my number" testContext testOptions []`
**Output**: 
`[Entity {dim = "time", body = "by 2.0", value = RVal Time (TimeValue (IntervalValue (InstantValue {vValue = 2013-02-12 04:30:00 -0200, vGrain = Second},InstantValue {vValue = 2013-02-12 14:00:00 -0200, vGrain = Second})) [IntervalValue (InstantValue {vValue = 2013-02-12 04:30:00 -0200, vGrain = Second},InstantValue {vValue = 2013-02-12 14:00:00 -0200, vGrain = Second})] Nothing), start = 3, end = 9, latent = False, enode = Node {nodeRange = Range 3 9, token = Token Time TimeData{latent=False, grain=NoGrain, form=Nothing, direction=Nothing, holiday=Nothing, hasTimezone=False}, children = [Node {nodeRange = Range 3 5, token = Token RegexMatch (GroupMatch []), children = [], rule = Nothing},Node {nodeRange = Range 6 9, token = Token Time TimeData{latent=True, grain=Hour, form=Just (TimeOfDay {hours = Just 2, is12H = True}), direction=Nothing, holiday=Nothing, hasTimezone=False}, children = [Node {nodeRange = Range 6 9, token = Token Numeral (NumeralData {value = 2.0, grain = Nothing, multipliable = False, okForAnyTime = True}), children = [Node {nodeRange = Range 6 9, token = Token RegexMatch (GroupMatch ["2.0"]), children = [], rule = Nothing}], rule = Just "decimal number"}], rule = Just "time-of-day (latent)"}], rule = Just "by <time>"}}]`

**Understanding**: Duckling parsed `by 2.0` as a Time entity since it matches this rule:

```haskell
ruleIntervalBy :: Rule
ruleIntervalBy = Rule
  { name = "by <time>"
  , pattern =
    [ regex "by"
    , dimension Time
    ]
  , prod = \tokens -> case tokens of
      (_:Token Time td:_) -> Token Time <$> interval TTime.Open now td
      _ -> Nothing
  }
```

**Question**:

1. Why doesn't the Numeral rule match against the second query `ok by 2.0 is my number`? It makes sense to return both the Time and Numeral match. My understanding is all rules that match a sequence of token should be returned.

2. Is there a way to return both latent and non-latent matches? Currently, it's either Latent OR non-Latent, but from the app dev perspective, its impossible to know which one to use for a given query.

**Comment by patapizza** [comment]
Hi @vijay120,

Sorry for the delay.

1. The `Numeral` rule does match that rule; it's in the parse tree of the final returned entity. Duckling returns the overarching tokens and not the intermediate results (which you could get through the parse tree). The rationale is that for `are you available tomorrow at 6pm`, we don't really care about getting `6` as a `Numeral` nor about `tomorrow` as an intermediate match: we want top-level entities. If you are looking for `Numeral` specifically, set the list of dimensions `[This Numeral]`.
2. By default, latent entities aren't returned. Set `withLatent = True` to get them, but here again `Time` would take over: you'd have to set `[This Temperature]`. To see all tokens found (including intermediate ones), use `allParses` from `Duckling.Debug`.
3. When the latent option is set, both latent and non-latent matches are returned. In this case, the `Time` entity takes over and is the only one returned.

Hope this helps.
