### ISSUE TITLE
Datetime year issue

### ISSUE THREAD

**Issue by nomercy89** [facebook/duckling#288]
I can't understand why the wit/datetime component gives me back two different years with two different ranges of months.

Look here: [link1](https://ibb.co/VqVZY2v) [link2](https://ibb.co/QKcJFRF)

Is there a way to return the current year if it is not specified **in wit.ai**? (As in link1)

Thanks

**Comment by patapizza** [comment]
Hi @nomercy89, Duckling follows the assumption that datetimes are in the future, unless there's no ambiguity that it's in the past. The ability to override assumptions is tracked in https://github.com/facebook/duckling/issues/29. In the mean time, you can pass a reference time in the context.
