### ISSUE TITLE
age_of_person parsing incorrect

### ISSUE THREAD

**Issue by DevinHillenius** [facebook/duckling#289]
I have implemented the built-in `age_of_person` entity in my Wit.ai application, it however does not work as I expected it to work. The entity matches with many random inputs with very high confidence ratings, see e.g.:
![image](https://user-images.githubusercontent.com/15893753/49331585-d495ea80-f59f-11e8-91f1-9f7bb18f47f0.png)

Especially singular words or small sentences that are not easily matched by other intents are often wrongly matched by the age_of_person entity.

Is this expected (buggy?) behaviour? Or did I do something wrong with the implementation of the entity?

**Comment by patapizza** [comment]
Hi @DevinHillenius, `wit/age_of_person` is not powered by Duckling. Please report the issue here: https://github.com/wit-ai/wit/issues
