### ISSUE TITLE
how can i add rule for percentage number

### ISSUE THREAD

**Issue by iorilu** [facebook/duckling#295]
I want to add percentage number rule for zh-CN , Chinese language

the target is simple , just identify a number with some regex like regex "(%|百分|个点)" , then multiply with 0.01, i copied some code ,but didn't work out.

here is the test I want to pass, Duckling/Numeral/ZH/Corpus.hs
examples (NumeralValue 0.05)
             [ "5%"
             , "5.0%"
             , "百分之五"
             , "百分之5"
             , "5个点"
             , "5个百分点"
             , "五个点"
             , "五个百分点"
             ]

rule I add , Duckling/Numeral/ZH/Rules.hs
ruleNumeralsPercentage :: Rule
ruleNumeralsPercentage = Rule
  { name = "numbers suffix with %"
  , pattern =
    [ regex "(%|百分|个点)"
    , dimension Numeral
    ]
  , prod = \case
      (_:Token Numeral nd:_) -> double (TNumeral.value nd * (1e-2))
      _ -> Nothing
  }

but can't make it work , can anyone help , I dont know haskell , currently hurry in project progress , thanks

**Comment by patapizza** [comment]
Hi @iorilu,

This look like the right direction - can you try swapping the patterns (both in the `pattern` section and the `prod` destructuring)? Right now it would parse "%5", not "5%".

**Comment by iorilu** [comment]
thanks ,  I made it work now , it can resolve 5% 

though there is still some issue , that's related to Chinese I think ,  I will check later , maybe I should learn some haskell
