### ISSUE TITLE
Running as Linux Service

### ISSUE THREAD

**Issue by joaodotneto** [facebook/duckling#303]
[duckling-service.zip](https://github.com/facebook/duckling/files/2706273/duckling-service.zip)

I'm trying to put Duckling to run as a linux service, but i'm so dumb about it.

I create a bash file, put it inside the duckling folder, create the service file, put it inside the system folder like this tutorial:
[https://medium.com/@sulmansarwar/run-your-java-application-as-a-service-on-ubuntu-544531bd6102](url)
But i got this error. Stack tries to install something:

> Dec 23 20:24:57 ip-10-19-10-197 systemd[1]: Started Duckling HTTP REST Service.
Dec 23 20:24:57 ip-10-19-10-197 stack[2324]: Downloading lts-9.10 build plan ...
Dec 23 20:24:58 ip-10-19-10-197 stack[2324]: Downloaded lts-9.10 build plan.
Dec 23 20:24:59 ip-10-19-10-197 stack[2324]: Preparing to install GHC to an isolated location.
Dec 23 20:24:59 ip-10-19-10-197 stack[2324]: This will not interfere with any system-level installation.
Dec 23 20:24:59 ip-10-19-10-197 stack[2324]: Preparing to download ghc-8.0.2 ...
Dec 23 20:25:00 ip-10-19-10-197 stack[2324]: ghc-8.0.2: download has begun
Dec 23 20:25:01 ip-10-19-10-197 stack[2324]: ghc-8.0.2:   34.51 MiB / 107.55 MiB ( 32.09%) downloaded...
Dec 23 20:25:02 ip-10-19-10-197 stack[2324]: ghc-8.0.2:   61.31 MiB / 107.55 MiB ( 57.01%) downloaded...
Dec 23 20:25:03 ip-10-19-10-197 stack[2324]: ghc-8.0.2:   93.80 MiB / 107.55 MiB ( 87.22%) downloaded...
Dec 23 20:25:03 ip-10-19-10-197 stack[2324]: ghc-8.0.2:  107.55 MiB / 107.55 MiB (100.00%) downloaded...
Dec 23 20:25:04 ip-10-19-10-197 stack[2324]: Downloaded ghc-8.0.2.
Dec 23 20:25:04 ip-10-19-10-197 stack[2324]: Unpacking GHC into /home/ubuntu/.stack/programs/x86_64-linux/ghc-8.0.2.temp/ ...
Dec 23 20:25:21 ip-10-19-10-197 stack[2324]: Configuring GHC ...
Dec 23 20:25:26 ip-10-19-10-197 stack[2324]: Installing GHC ...
Dec 23 20:25:27 ip-10-19-10-197 stack[2324]: Received ExitFailure 2 when running
Dec 23 20:25:27 ip-10-19-10-197 stack[2324]: Raw command: /usr/bin/make install
Dec 23 20:25:27 ip-10-19-10-197 stack[2324]: Run from: /home/ubuntu/.stack/programs/x86_64-linux/ghc-8.0.2.temp/ghc-8.0.2/
Dec 23 20:25:27 ip-10-19-10-197 systemd[1]: duckling-http.service: Main process exited, code=exited, status=1/FAILURE
Dec 23 20:25:27 ip-10-19-10-197 systemd[1]: duckling-http.service: Failed with result 'exit-code'.

What i'm doing wrong?
Thanks in advance.

**Comment by chessai** [comment]
The failure is obscured here. Try building duckling on your system and pasting the _full_ error output.

**Comment by joaodotneto** [comment]
> The failure is obscured here. Try building duckling on your system and pasting the _full_ error output.

Thanks for the answer, but my question is asked in 2018.
I don't even know what became of this project in the company.
