### ISSUE TITLE
Number or Time/date period identification in Duckling

### ISSUE THREAD

**Issue by Greg3108** [facebook/duckling#305]
A duckling tries to extract as many entity types as possible without providing a ranking. For example, if you specify both number and time as dimensions for the duckling component, the component will extract two entities: 10 as a number and in 10 minutes as a time from the text "I will be there in 10 minutes". In such a situation. my application would have to decide which entity type is be the correct one.  How can I set priority in duckling based on dimension? I want only one entity from the text. is there any way to get only one entity? 

Many thanks in advance.

**Comment by chessai** [comment]
My advice is to look at the start and end fields of the Entity object. Whichever has the larger breadth, is probably what you should choose. This is a simple heuristic that should work well for most cases.

Closing as not actionable from duckling side.
