### ISSUE TITLE
Repeated consecutive ZH characters causes failure to parse

### ISSUE THREAD

**Issue by ysze** [facebook/duckling#313]
To give a simple example,

in duckling/Duckling/Ordinal/ZH/Rules.hs,

the pattern is

    [ regex "第"
    , dimension Numeral
    ]

Naturally, an example such as "第七" will work properly. In general, "第七[any character other than 七]" or "[any character other than 第]第七" will work properly.

However, something like "第第七" will fail. Similarly, "第七七" will fail.

**Comment by ysze** [comment]
Hi @haoxuany 

Thanks for your response. I understand the basis of your reasoning, but I don't quite agree with you on the reason Duckling is failing to parse "第七七". By your argument, neither is "七第七" or "阿第七" correct Chinese, but in those cases "第七" can be successfully extracted.

Thanks!

**Comment by haoxuany** [comment]
Hi @ysze, @hchings,

Looks like you're right! For some reason partial parsing lookup is specifically failing to start at the right chinese character.

I suspect this is likely something in the regex engine in `Duckling/Engine.hs`, the `lookupItemAnywhere` and `matchFirstAnywhere` function, although I haven't had the time to dive deep into this.

Would you be interested in taking a look? It may be helpful to insert a `Debug.trace` for debugging.

Thank you!

**Comment by wtjones382** [comment]
I know y'all are stealing shit so I advise u chill bc Spartanburg county
police force is looking into your credit card and other activities are
being watched!!!!
