### ISSUE TITLE
Dealing with Prefix/Suffix

### ISSUE THREAD

**Issue by rinn7e** [facebook/duckling#315]
I am wondering if we could create a rule to handle prefix/suffix with a word. An example of this is dealing with Finnish Datetime.

In Finnish the phrase `January` would be `tammikuu` and `in january` would be `tammikuussa` with a `-ssa` suffix. 

Can anyone help on this ?

**Comment by chessai** [comment]
Seems like you want a rule for something specific, and in the general case there is nothing to do. 

Closing as not actionable.
