### ISSUE TITLE
Failed to build on Windows 10

### ISSUE THREAD

**Issue by 91ns** [facebook/duckling#316]
I'm trying to run Duckling on Windows 10 but I got this error message : 

Preprocessing executable 'custom-dimension-example' for duckling-0.1.6.1...
[1 of 1] Compiling Main             ( exe\CustomDimensionExample.hs, .stack-work\dist\ca59d0ab\build\custom-dimension-example\custom-dimension-example-tmp\Main.o )
Linking .stack-work\dist\ca59d0ab\build\custom-dimension-example\custom-dimension-example.exe ...
C:\Users\dell\Documents\duckling_\.stack-work\dist\ca59d0ab\build/libHSduckling-0.1.6.1-Ft93d1YJVzHJVWz85XZVhK.a(Dimensions.o):fake:(.text+0x140): undefined reference to `ducklingzm0zi1zi6zi1zmFt93d1YJVzzHJVWzz85XZZVhK_DucklingziDimensionsziSW_allDimensions_closure'
collect2.exe: error: ld returned 1 exit status
`gcc.exe' failed in phase `Linker'. (Exit code: 1)

--  While building custom Setup.hs for package duckling-0.1.6.1 using:
      C:\sr\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_1.24.2.0_ghc-8.0.2.exe --builddir=.stack-work\dist\ca59d0ab build lib:duckling exe:custom-dimension-example exe:duckling-example-exe exe:duckling-expensive exe:duckling-regen-exe exe:duckling-request-sample --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1

**Comment by cowjen01** [comment]
I've got the same problem. Building on macOS Mojave 10.14.2 (18C54)

`Undefined symbols for architecture x86_64:
  "_ducklingzm0zi1zi6zi1zmFuuoxNkK08bIA0dGJuhBV1_DucklingziDimensionsziSW_allDimensions_closure", referenced from:
      _se3Xu_info in libHSduckling-0.1.6.1-FuuoxNkK08bIA0dGJuhBV1.a(Dimensions.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`gcc' failed in phase `Linker'. (Exit code: 1)`

`While building package duckling-0.1.6.1 using:
      /Users/jean/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.24.2.0 build lib:duckling exe:custom-dimension-example exe:duckling-example-exe exe:duckling-expensive exe:duckling-regen-exe exe:duckling-request-sample --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1`

**Comment by cowjen01** [comment]
Fixed by adding `, Duckling.Dimensions.SW` into the **duckling.cabal** file.

**Comment by 91ns** [comment]
@cowjen01 that actually helped, but now I have another problem when I run 

stack exec duckling-example-exe

duckling-example-exe.EXE: /usr/share/zoneinfo/: getDirectoryContents:findFirstFile: does not exist (The system cannot find the path specified.)

did you run into the same issue on macOS?

**Comment by cowjen01** [comment]
No, after the edit of duckling.cabal file everythink was fine. I’d try to run ‘stack clean’ and than ‘stack build’. Or checkout PATH variable settings.

**Comment by Rajskc** [comment]
@91ns Hey is this issue resolved?

**Comment by 91ns** [comment]
@Rajskc no I'm still unable to run duckling on Windows 10.

stack exec duckling-example-exe

duckling-example-exe.EXE: /usr/share/zoneinfo/: getDirectoryContents:findFirstFile: does not exist (The system cannot find the path specified.)

As an alternative way to make it work I tried to run duckling in a docker container, it successfully built but when I try to run duckling-example-exe

I get this : 
...
Listening on 0.0.0.0:8000 

But when I try to hit the endpoint it returns "Connection refused"

**Comment by Rajskc** [comment]
@91ns  Thanks for your reply. I will try in ubuntu and see if it's working.

**Comment by mekyush** [comment]
@91ns Are you able to get response from 0.0.0.0:8000. I am getting the same error

**Comment by 91ns** [comment]
@mekyush no, it never worked out on my end. But I haven't tried again after that, I'll be giving it another shot soon and will post updates if any.

**Comment by 91ns** [comment]
@mekyush the solution here actually worked out for me https://github.com/facebook/duckling/issues/349

**Comment by chessai** [comment]
Closing as the reported issue is resolved, remaining issue is in #349
