### ISSUE TITLE
False positives for 'TIME' dimension

### ISSUE THREAD

**Issue by cmvignesh** [facebook/duckling#323]
When a sentence such as "That's the first school I've ever been to" or "The second most important" is sent to parse, duckling wrongly interprets 'the first' and 'The second' as days of the subsequent month. The same happens for inputs containing 'from first', 'from second' etc. as well.

Example:
Response for "That's the first school I've ever been to":

```
[
    {
        "body": "the first",
        "dim": "time",
        "end": 16,
        "latent": false,
        "start": 7,
        "value": {
            "grain": "day",
            "type": "value",
            "value": "2019-02-01T00:00:00.000+00:00",
            "values": [
                {
                    "grain": "day",
                    "type": "value",
                    "value": "2019-02-01T00:00:00.000+00:00"
                },
                {
                    "grain": "day",
                    "type": "value",
                    "value": "2019-03-01T00:00:00.000+00:00"
                },
                {
                    "grain": "day",
                    "type": "value",
                    "value": "2019-04-01T00:00:00.000+00:00"
                }
            ]
        }
    }
]
```

**Comment by cristicbz** [comment]
A similar example to this is `To whom this may concern`, where `this may` gets picked up as a date . This does ultimately seem like a fundamental limitation of the design here, so I'm not sure there's any real resolution for these cases.

**Comment by mollerhoj** [comment]
The rule-based design obviously has some limitations, but I don't see why we shouldn't try and take it as far as possible - e.g. in @cristicbz 's example, we could have predicate that makes it so `this may` is not extracted if it is preceded by `whom`.

**Comment by chessai** [comment]
closing as wontfix
