### ISSUE TITLE
[AmountOfMoney] Missing extraction of CAD and CHF

### ISSUE THREAD

**Issue by annesylvie** [facebook/duckling#326]
When using the `duckling-example-exe` provided in the repository, it seems that some currencies (in particular `CHF` and `CAD`) are not correctly extracted (extracted as `number` instead of `amount-of-money`).

## Steps to reproduce
Clone the repository, build and execute `duckling-example-exe`.
-  `curl -XPOST http://0.0.0.0:8000/parse --data 'text=I have 5 chf'` returns a `number` dimension.
-  `curl -XPOST http://0.0.0.0:8000/parse --data 'text=I have 5 cad'` returns a `number` dimension as well.
-  On the other hand, `curl -XPOST http://0.0.0.0:8000/parse --data 'text=I have 5 usd'` returns a (correct) `amount-of-money` dimension. Same for `jpy`, and other less common currencies such as `mad`, `egp`...

I still get the same behaviour even if I try to specify a `locale`.

Looking through the repository though I do not see a difference in the way say `EGP` and `CAD` are implemented, so I am a bit at loss on what is happening here. Am I missing something?
Thanks in advance for any help.

**Comment by patapizza** [comment]
Thanks for reporting @annesylvie! This is now fixed thanks to @tommilligan.
