### ISSUE TITLE
New releases?

### ISSUE THREAD

**Issue by faheem-nadeem** [facebook/duckling#328]
Awesome library, thanks for this.

Any chance for getting regular releases. The last one seems to be pretty old. We have been building ourselves for some time and there are a bunch of docker images out there, better to have an official one.

This can also be combined with #241 for automatic image pushes to dockerhub, at least for latest and release tags.

**Comment by tommilligan** [comment]
Could someone on the team provide an ETA of next release? Or comment on if `master` is considered stable for building from directly?

@haoxuany

**Comment by beevelop** [comment]
Any update in 2020?

**Comment by chessai** [comment]
I am working on getting a release out this week, with more consistent relelases going forward.

**Comment by chessai** [comment]
https://github.com/facebook/duckling/releases/tag/v0.2.0.0

https://hackage.haskell.org/package/duckling-0.2.0.0
