### ISSUE TITLE
end of the month/ende des Monats gives wrong result.

### ISSUE THREAD

**Issue by mauricedoepke** [facebook/duckling#337]
I would expect this to return the last day of the current month, but it returns the first day of the next month.

**Comment by paddotk** [comment]
What is 'this'? You'll have to provide a bit more info.

**Comment by mauricedoepke** [comment]
This means what I wrote in the title:
"end of the month/ende des Monats gives wrong result"

**Comment by chessai** [comment]
intervals in duckling are upper-exclusive, that's why you're seeing this.
