### ISSUE TITLE
Wit ai which uses duckling to recognize the amount of money is not working as expected.

### ISSUE THREAD

**Issue by JeevaTM** [facebook/duckling#340]
I am currently training Wit to recognize different entities.

While I came across this error from automatic recognition,

Input: "Part of the Mahindra Group, Tech Mahindra is a US$4.7 billion company[3] with over 113,550 employees across 90 countries."

"US$4.7 billion" is automatically recognized as "USD47000001"

**Comment by patapizza** [comment]
Thanks for reporting @JeevaTM! We'll look into this.
