### ISSUE TITLE
Inquiry about a extracting trained useful files only

### ISSUE THREAD

**Issue by A7medBahgat** [facebook/duckling#342]
Are there any way to avoid downloading the whole repo to use duckling in my chatbot which is built with rasa framework, I was thinking maybe there's some way to extract a .bin callable file or something and call it instead of having all off those files inside my project.

**Comment by chessai** [comment]
There are a few options

1. Host it in a server somewhere
2. Run it as a system level docker service
3. Call the code natively (haskell only)

Closing because this is not actionable on duckling's side
