### ISSUE TITLE
Duckling support for multiple time zones

### ISSUE THREAD

**Issue by mike23333** [facebook/duckling#344]
Hi,

When will duckling support for multiple time zones be available? And is there any workarounds to handle users from different timezones since it seems duckling only supports one timezone?

Thanks

**Comment by mauricedoepke** [comment]
Duckling already supports timezones. U can use all time zones that are available in the folder: /usr/share/zoneinfo

Use them by adding them as a request parameter, like this:
tz=Europe/Berlin

**Comment by chessai** [comment]
Like @mauricedoepke says, duckling supports timezones already.
