### ISSUE TITLE
Time reftime ignore into special cases

### ISSUE THREAD

**Issue by marco25d** [facebook/duckling#345]
I would not utilized the specified reftime if I found special pattern match. For example not using reftime with "tomorrow" but still use it with "wednesday". Could be possible? I've seen the TimeData as a boolean parameter notImmediate, if I could be able to set it to False Does it consider reftime now or not?

**Comment by marco25d** [comment]
I had a look to ExampleMain.hs where it is inizialized a parameter named context with the locale current time and the reference setted time. Is that the one who is used into the Time/Helpers.hs at the function takeNth to find the time?

**Comment by justinphan3110** [comment]
So the takeNth function return mkSeriesPredicate series, do you have any idea we can't get specific date value like tdMonth or Year from this ?
