### ISSUE TITLE
Datetime format `DD month YY` not supported for `fr-FR`

### ISSUE THREAD

**Issue by amenella** [facebook/duckling#347]
Hi,

We observed that datetime format `DD month YY` was not parsed for `fr-FR` language.

Tests results:
- **SUCCESS** `le 18 juin 1989` [fr-FR]  `1989-06-18T00:00:00.000+02:00`
- **SUCCESS** `18/06/89` [fr-FR] `1989-06-18T00:00:00.000+02:00`
- **SUCCESS** `18th june 89` [en-US]  `1989-06-18T00:00:00.000+02:00`
- **FAILURE** `le 18 juin 89` [fr-FR] XXX

Would you have any idea of which Rule is implicated ?

Best regards,

**Comment by amenella** [comment]
Any hints on this ?
Is is a missing rule for french or an issue ?

**Comment by chessai** [comment]
See https://github.com/facebook/duckling/pull/357#issuecomment-777833888 for why this might be problematic. I don't know of a way to get this to work without causing unnecessary matches yet.

**Comment by chessai** [comment]
Actually, #357 just needs a more inclusive rule than it currently has.
