### ISSUE TITLE
Turkish date extraction

### ISSUE THREAD

**Issue by maxbry** [facebook/duckling#348]
Hello,

has there been work on Turkish date extraction?

Thank you!

**Comment by patapizza** [comment]
Hi @maxbry,

`Time` doesn't exist yet for TR, but all other dependent dimensions (e.g. [`Duration`](https://github.com/facebook/duckling/blob/master/Duckling/Dimensions/TR.hs#L18)) are there! Feel free to get a stab at it.

**Comment by chessai** [comment]
this is in master now
