### ISSUE TITLE
Different results from duckling.wit.ai and local

### ISSUE THREAD

**Issue by marcoaleixo** [facebook/duckling#353]
Currently I'm calling the Duckling with this string "............... ao Em  05  de julho  de  2017,  o Para conferir o original, acesse o site ......... ", this is a Portuguese language, and the result of the Duckling API is 
``
{  
   "body":"2017",
   "start":93,
   "value":{  
      "values":[  
         {  
            "value":"2017-01-01T00:00:00.000-08:00",
            "grain":"year",
            "type":"value"
         }
      ],
      "value":"2017-01-01T00:00:00.000-08:00",
      "grain":"year",
      "type":"value"
   },
   "end":97,
   "dim":"time"
}
``
To make this call I'm using the "rasa/duckling" docker image and passing locale as "PT".

But, when I pass the same string to the duckling.wit.ai the result is correct

![correto](https://user-images.githubusercontent.com/19698739/55187779-a5237300-5178-11e9-80cb-b0ac90aa27f1.png)

Any idea?

**Comment by tushar-semwal** [comment]
I have the exact same issue for English sentences. For example "Can you please show the pressure values for Limpet 9 from 8 April to  2 June 2019" is detected as:
With Local RASA: 
```
{
      "start": 50,
      "end": 80,
      "text": "9 from 8 April to  2 June 2019",
      "value": "2019-04-08T09:00:00.000-07:00",
      "confidence": 1.0,
      "additional_info": {
        "values": [
          {
            "value": "2019-04-08T09:00:00.000-07:00",
            "grain": "hour",
            "type": "value"
          },
          {
            "value": "2019-04-08T21:00:00.000-07:00",
            "grain": "hour",
            "type": "value"
          },
          {
            "value": "2019-04-09T09:00:00.000-07:00",
            "grain": "hour",
            "type": "value"
          }
        ],
        "value": "2019-04-08T09:00:00.000-07:00",
        "grain": "hour",
        "type": "value"
      },
      "entity": "time",
      "extractor": "DucklingHTTPExtractor"
    }
```

With duckling.wit.ai: 

![Capture](https://user-images.githubusercontent.com/8556809/61283959-e4bcac00-a7b5-11e9-8e3c-b44832d8623d.PNG)

Any help is appreciated. 
Thanks.

**Comment by turbolent** [comment]
That website is for an older version (written in Clojure)

**Comment by chessai** [comment]
closing in favour of tracking ticket #589
