### ISSUE TITLE
Arabic numerals are not supported

### ISSUE THREAD

**Issue by amragaey** [facebook/duckling#355]
Hello,

I was trying to parse arabic numerals like '١,  ٢, ٣..' but it returns empty response.

I checked the code, it seems there's a mapping [here](https://github.com/facebook/duckling/blob/master/Duckling/Numeral/AR/Helpers.hs#L28) but it has no usage! So I think we have to add a rule for arabic numerals like ruleDecimalNumeral. We would ideally match unicode unicode letters in this range [\1632-\1641].

Let me know if we can do it!

Thanks

**Comment by nathanhausman** [comment]
Hi amragaey, 

This feature is now supported. Check out [this commit](https://github.com/facebook/duckling/commit/f6399c84629e4b71f16bde19670e8e312dcec14f) and [this commit](https://github.com/facebook/duckling/commit/cbfca8ccc34668671988ac405fca92e9fbcb5065) for more details
