### ISSUE TITLE
[phone_number] recognize "five three zero..." as phone number

### ISSUE THREAD

**Issue by aforaleka** [facebook/duckling#356]
Reposting from wit.ai https://github.com/wit-ai/wit/issues/1409

> current behavior:
> when wit.ai transcribes a spoken phone number string, it returns the phone number as a text string. for example the transcription might look like: "please call me back at seven one eight five five five one two one two". this, in and of itself, is not a problem. however, the wit/phone_number entity does not recognize this as a phone number.
> 
> steps to reproduce:
> post audio to the speech endpoint that contains a phone number
> 
> expected behavior:
> i would either expect phone numbers to be transcribed like "718-555-1212" OR wit/phone_number entity to recognize phone numbers formatted like "please call me back at seven one eight five five five one two one two".
> 
> for the time being i'm using https://www.npmjs.com/package/words-to-numbers to take the transcribed text, reformat it, and re-post the number-ified transcription back into wit. this works, but means i'm querying wit twice, and feels like something wit should handle natively.

**Comment by abv** [comment]
Here is an other similar issue:

Wit.ai transcribes a DOB as follows: "august twenty third nineteen eighty" Seems to handle day and month ok, but not year. Is looks like the year (in this case 1980) isn't properly parsed.

{
	"_text": "august twenty third nineteen eighty",
	"entities": {
		"datetime": [{
			"confidence": 1,
			"values": [{
				"value": "2019-08-23T00:00:00.000-04:00",
				"grain": "day",
				"type": "value"
			}, {
				"value": "2020-08-23T00:00:00.000-04:00",
				"grain": "day",
				"type": "value"
			}, {
				"value": "2021-08-23T00:00:00.000-04:00",
				"grain": "day",
				"type": "value"
			}],
			"value": "2019-08-23T00:00:00.000-04:00",
			"grain": "day",
			"type": "value"
		}]
	},
	"msg_id": "1LqImkjGlBD7V7rXO"
}

**Comment by chessai** [comment]
This is a wit issue. Not sure why this was copied here. Duckling isn't responsible for how wit decided to encode things. only decode.
