### ISSUE TITLE
Date normalization

### ISSUE THREAD

**Issue by warzocha** [facebook/duckling#363]
Hi!

Is there an option which allows user to decide how the **Date** and **Time** are normalized by Duckling? If not, I believe, it would be nice to have it.

E.g.:
"On Sunday", as an answer for a question, can mean "next Sunday" or "last Sunday" depending on the question.

**Comment by haoxuany** [comment]
Hi @warzocha,

I believe at the moment this is unsupported, since the primary purpose of duckling is to parse specific dimensions rather than to analyze contexts. If you have a nice solution to this, feel free to let us know! 😄

**Comment by chessai** [comment]
Yes, like @haoxuany puts, this is beyond the scope of duckling.
