### ISSUE TITLE
Incorrect Quarter Date in Duckling

### ISSUE THREAD

**Issue by anurag53** [facebook/duckling#364]
Hi,
I am using duckling for date parsing with Rasa. For phrase like 'list all products sold in Quarter 1 2018', the duckling is capturing multiple cases like 'in Quarter 1' and 'Quarter 1 2018' for date and giving respective multiple dates as "2019-07-01" and "2018-01-01".

Please help me to get the correct date. Thanks in advance.

**Comment by patapizza** [comment]
Hi @anurag53,

Duckling returns the `grain` information as well as the resolved datetime. The first quarter of the year starts on 1/1, the third one on 7/1, etc. Using the start date and the grain, you should be able to compute the upper bound date. Hope this helps.
