### ISSUE TITLE
Parsing set of digits as phone number only

### ISSUE THREAD

**Issue by Zylatis** [facebook/duckling#365]
If i give text of '10 10 10' it parses this as phone number, which is fine, but it _only_ gives a phone number and not the 3 numbers. I understand this is a simple thing i can just do with normal python, but it would be nice to have it all under one roof (I want to use this in conjunction with duckling getting distances)

Is this the expected output? Alternatively, can i force it to only consider numbers and distances?

Thanks,
Z

**Comment by chessai** [comment]
Duckling server on master will return every potential dimension by default.
