### ISSUE TITLE
Different results from duckling.wit.ai and ducking docker using local

### ISSUE THREAD

**Issue by anurag53** [facebook/duckling#370]
Hi, I am using Duckling API for parsing date along with rasa NLU.

I’m calling the Duckling with this string "Mumbai Sales may’ and the result of the Duckling API is [].

To make this call I’m using the “rasa/duckling” docker image and passing locale as “en_IN”.

But, when I pass the same string to the duckling.wit.ai the result is correct

![image](https://user-images.githubusercontent.com/46107240/57585138-b2ff3e80-7501-11e9-80db-495b1aab4c9e.png)

How can this be resolved?

Which version of duckling docker duckling.wit.ai is using?

How can I get the ducking docker version I am running?

Please help.

**Comment by patapizza** [comment]
Hi @anurag53,

We still need to prioritize upgrading `duckling.wit.ai` to use this repo (tracked in https://github.com/wit-ai/wit/issues/1208).

I believe the docker image you're using is based off https://github.com/RasaHQ/duckling, which is a fork from this repo.

`may` has been turned `latent` as it's too common in English. To get latent results, turn on the `latent` flag when issuing requests.
