### ISSUE TITLE
ES numerals aren't recognised when separated

### ISSUE THREAD

**Issue by sony2** [facebook/duckling#380]
When I write some numbers duckling doesn't recognize the numbers separated.

**Examples:**
doscientos tres -> 203
<class 'list'>: [{'body': 'doscientos', 'start': 0, 'value': {'value': 200, 'type': 'value'}, 'end': 10, 'dim': 'number', 'latent': False}, {'body': 'tres', 'start': 11, 'value': {'value': 3, 'type': 'value'}, 'end': 15, 'dim': 'number', 'latent': False}]

mil novecientos noventa y tres -> 1993
<class 'list'>: [{'body': 'mil', 'start': 0, 'value': {'value': 1000, 'type': 'value'}, 'end': 3, 'dim': 'number', 'latent': False}, {'body': 'mil', 'start': 0, 'value': {'values': [{'value': '1000-01-01T00:00:00.000-07:53', 'grain': 'year', 'type': 'value'}], 'value': '1000-01-01T00:00:00.000-07:53', 'grain': 'year', 'type': 'value'}, 'end': 3, 'dim': 'time', 'latent': False}, {'body': 'novecientos', 'start': 4, 'value': {'value': 900, 'type': 'value'}, 'end': 15, 'dim': 'number', 'latent': False}, {'body': 'noventa y tres', 'start': 16, 'value': {'value': 93, 'type': 'value'}, 'end': 30, 'dim': 'number', 'latent': False}]

**Comment by chessai** [comment]
I updated your comment to say "doesn't" (it was omitted before) to reflect the intent of the issue.

**Comment by chessai** [comment]
Updated title to be less vague and indicative of the issue
