### ISSUE TITLE
Date Range is not working

### ISSUE THREAD

**Issue by landman** [facebook/duckling#385]
Hi, i m working on a booking site in german and the user should also search with free text.
For example: "Suche Flug vom 12. bis 18. August von Berlin nach New York" but wit did not understand the first Number in a Date Range. For example:

![60641569-a249b580-9e2c-11e9-8eed-a10ce6e2f870](https://user-images.githubusercontent.com/5006372/61135078-3cf76380-a4c1-11e9-8f5a-a85d6197a033.png)

I tried different dates but its not working. How can i train it?

One date is working. For example: ""Suche Hotel am 12. August in Berlin".

Thanks and Best from Berlin, Dennis

**Comment by patapizza** [comment]
Hi @landman,

Sorry for the latency. I just tried `Suche Flug vom 12. bis 18. August von Berlin nach New York` and it is working now.

**Comment by landman** [comment]
Hi, no its not working :( I tried it different times and also on the test console on https://duckling.wit.ai/. 
![Bildschirmfoto 2019-11-20 um 13 40 52](https://user-images.githubusercontent.com/5006372/69239830-6759db80-0b9b-11ea-80a3-a26e3d6f0861.png)
