### ISSUE TITLE
C bindings

### ISSUE THREAD

**Issue by turbolent** [facebook/duckling#386]
I created C bindings and released them here: https://github.com/turbolent/CDuckling

However, when building Duckling, the resulting library is ~180MB. 

Is this normal and expected? I was hoping to embed Duckling into another program, but this is quite large. Is there any way to build a smaller library?

**Comment by chessai** [comment]
Wow! Thank you for this effort. I will close #49

GHC typically produces binaries of larger size (unfortunately).

1. How are you building the duckling library?
2. Can you try linking against the library and stripping the code, and seeing how much gets stripped off?

**Comment by chessai** [comment]
Oops, didn't mean to close for now.

**Comment by chessai** [comment]
Closing as not actionable on the duckling side
