### ISSUE TITLE
Different results for facebook/duckling local binary and duckling.wit.ai

### ISSUE THREAD

**Issue by tushar-semwal** [facebook/duckling#387]
I compiled the duckling binary from the facebook/duckling repo and then tested the local duckling. My utterance is:
"Can you please show the pressure values for Limpet 9 from 8 April to  2 June 2019" 

With Local duckling tool, the detected text is "9 from 8 April to  2 June 2019" which is incorrect as the 9 is extra here. See below for more details.
```
{
      "start": 50,
      "end": 80,
      "text": "9 from 8 April to  2 June 2019",
      "value": "2019-04-08T09:00:00.000-07:00",
      "confidence": 1.0,
      "additional_info": {
        "values": [
          {
            "value": "2019-04-08T09:00:00.000-07:00",
            "grain": "hour",
            "type": "value"
          },
          {
            "value": "2019-04-08T21:00:00.000-07:00",
            "grain": "hour",
            "type": "value"
          },
          {
            "value": "2019-04-09T09:00:00.000-07:00",
            "grain": "hour",
            "type": "value"
          }
        ],
        "value": "2019-04-08T09:00:00.000-07:00",
        "grain": "hour",
        "type": "value"
      },
      "entity": "time",
      "extractor": "DucklingHTTPExtractor"
    }
```

However, With duckling.wit.ai the result is correct. See the image below:

![Capture](https://user-images.githubusercontent.com/8556809/61283959-e4bcac00-a7b5-11e9-8e3c-b44832d8623d.PNG)

Any help is appreciated. 
Thanks.

**Comment by patapizza** [comment]
The website is still using the legacy Clojure version; we haven't had the chance to prioritize wiring up the Haskell library (https://github.com/facebook/duckling/issues/353).
Keeping this one open as a bug.

**Comment by chessai** [comment]
Closing in favour of #589 (tracking issue for all bugs related to this)
