### ISSUE TITLE
Types.hs#runTimeIntervalsPredicate retrieves future interval

### ISSUE THREAD

**Issue by tonyflow** [facebook/duckling#391]
Let's say that the date today is the 23rd of July 2019. If we were to process with Duckling a phrase like "from January to February", Duckling would link this to the next year: that is, from January 2020 to February 2020. This is because the time segment from January to February for 2019 is already in the past and the following method picks the first interval after the specified time segment.

```
runTimeIntervalsPredicate
  :: TimeIntervalType -> Predicate
  -> Predicate -> SeriesPredicate
runTimeIntervalsPredicate intervalType pred1 pred2 = timeSeqMap True f pred1
  where
    -- Pick the first interval *after* the given time segment
    f thisSegment ctx = case runPredicate pred2 thisSegment ctx of
      (_, firstFuture:_) -> Just $
        timeInterval intervalType thisSegment firstFuture
      _ -> Nothing
```
So the question here is: How do I stop this shifting towards a future date range?

I expect the result to be January 2019 - February 2019

**Comment by chessai** [comment]
It is currently not possible without modifying your input. This requires assumptions override, which is detailed more in #29

**Comment by chessai** [comment]
Closing in favour of #29
