### ISSUE TITLE
problem with Vietnamese date extraction

### ISSUE THREAD

**Issue by tungmaiv** [facebook/duckling#392]
when I posted:
- "Ngày hôm nay"= today: it returns the day after yesterday  - today is 2019-0-/26, the result is 2019-07-25.
- "hôm nay"= today: it returns the day after yesterday  - today is 2019-0-/26, the result is 2019-07-25.
- "Ngày hôm qua"= yesterday: it returns the day after yesterday  - today is 2019-0-/26, the result is 2019-07-24.
- "Một ngày trước" = "one day ago": it returns the day after yesterday  - today is 2019-0-/26, the result is 2019-07-24.
- "2  ngày trước " = "two days ago": it returns  3 days ago: today is 2019-0-/26, result is 2019-07-23.

**Comment by linh0866847550** [comment]
check GMT (default duckling is : -7)

**Comment by chessai** [comment]
The server will not have this issue. The library debugger by default pins the current time to remain pure (ie not have to fetch system time).
