### ISSUE TITLE
Delay 1 hour

### ISSUE THREAD

**Issue by letanloc1998** [facebook/duckling#393]
from 2pm today to 4pm tomorrow

=> From Saturday, 27 July 2019 at 14:00:00 -0700 (-07:00) to Sunday, 28 July 2019 at 17:00:00 -0700 (-07:00) :hour

why 4pm is 17:00:00 ?? Does anyone help me? Thanks

**Comment by letanloc1998** [comment]
![image](https://user-images.githubusercontent.com/26348718/62114409-cfc93800-b2e0-11e9-9417-5725e4679d56.png)

![image](https://user-images.githubusercontent.com/26348718/62114541-10c14c80-b2e1-11e9-8f67-a25623e563ea.png)

**Comment by patapizza** [comment]
See https://github.com/facebook/duckling/issues/178.

**Comment by letanloc1998** [comment]
> See #178.

Thank you
