### ISSUE TITLE
Does duckling works in dates expressed in non english language ?

### ISSUE THREAD

**Issue by DomLah** [facebook/duckling#398]
I'm wondering whether duckling would work for me.

I'm interested in entity extraction including dates expressed in French like: 
- le 15 Aout 2018
- le dix-huit Janvier mille neuf cent quatre vingt dix neuf.

Is it already supported?

**Comment by haoxuany** [comment]
Hi @DomLah, I'm not a french speaker, but I believe the specific phrases you have are supported to some degree, see [French Time Corpus](https://github.com/facebook/duckling/blob/master/Duckling/Time/FR/Rules.hs).

**Comment by DomLah** [comment]
Thanks for your response.
