### ISSUE TITLE
Support unit-of-duration with ordinals.

### ISSUE THREAD

**Issue by chetanyakan** [facebook/duckling#400]
## Summary
Duckling does not detect intervals with ordinals.

## Reproduction Steps
Check the entity for: `Every fifth week` in https://duckling.wit.ai

## Expected Output
- Entity: Interval
- Value: 5
- Unit: Week

## Actual Output
Duckling returns: `fifth day of the next month`.

## Screenshots
![image](https://user-images.githubusercontent.com/35728906/63015426-87984100-beae-11e9-8a80-60406f7ab0b3.png)

**Comment by chessai** [comment]
"Every 5th week" isn't really an interval, but rather a recurring series of times. I don't see why this would return an interval.

**Comment by chessai** [comment]
It isn't clear to me what duckling should do here. If you have any ideas, let me know.
