### ISSUE TITLE
Build a single language

### ISSUE THREAD

**Issue by Krogsager** [facebook/duckling#404]
Is it possible to just compile for a single language when calling make? Say, if I only want Danish.
What is actually happening when I call `stack build`?

**Comment by mauricedoepke** [comment]
One way would be to comment out all other language files in the cabal file and everywhere where they are imported. This is a bit time consuming but works. I just did the same for another language.

**Comment by Krogsager** [comment]
Cool, I will give that a try.

**Comment by kercos** [comment]
Hi, it seems to me a rather complex procedure to comment out all references to other languages. Would it be possible to set up a config variable where to specify the languages to build? I understand it make require quite an extensive refactoring of the code, but I think it would be a very useful feature.
