### ISSUE TITLE
Incorrect date when using from date to date

### ISSUE THREAD

**Issue by wbelhomsi** [facebook/duckling#407]
Hello,

I've been using wit.ai that uses duckling for date time and i've been encountering some problems with the from date to date.
Here are multiple examples with date being correct if written alone but incorrect if written in a form of from date x to date y (example from today to tomorrow)

![Only Writing Tomorrow](https://user-images.githubusercontent.com/40052755/64529985-c639e380-d314-11e9-9c7e-bb5dbf7b1a74.png)

![From Today to Tomorrow](https://user-images.githubusercontent.com/40052755/64529995-cafe9780-d314-11e9-821f-28c3ef05cf02.png)

![Writing a single date](https://user-images.githubusercontent.com/40052755/64530034-dce03a80-d314-11e9-80d9-f0c521e103b0.png)

![From Date to Date](https://user-images.githubusercontent.com/40052755/64530065-ec5f8380-d314-11e9-9b16-d60413cfa496.png)

Thanks for your help!

**Comment by llermaly** [comment]
This could help you : https://github.com/facebook/duckling/issues/171

**Comment by chessai** [comment]
Closing as a wit issue, if you're using the api follow the instructions in #171
