### ISSUE TITLE
Non-US dates are not extracted

### ISSUE THREAD

**Issue by nbeuchat** [facebook/duckling#413]
Dates in the format `dd/mm` or `dd/mm/yyyy` are not extracted at all by Duckling if the day is between 13 and 31. 

Only numbers are extracted for the following examples:

- 15/12
- 15/12/2019

In the previous examples, there is no ambiguity and even a US date parser should understand it. 

For context, we are using Duckling to extract dates and other entities in a chatbot. The bot can ask for confirmation if there is any ambiguity. Most of our users are Americans and use the US format but we have a few users from Europe who writes with the format `dd/mm` or `dd/mm/yyyy`

**Comment by DigiSenseiZim** [comment]
Any workaround to this yet?

**Comment by nbeuchat** [comment]
I haven't found any so far, would love to

**Comment by chessai** [comment]
Are you setting the locale to something other than en_US?

**Comment by chessai** [comment]
Exactly how are you querying duckling

**Comment by chessai** [comment]
Closing, this is very likely a locale issue. If you set the locale to eg en_GB you would be able to parse dates like this appropriately. Feel free to re-open if this is not the case for you.
