### ISSUE TITLE
Build a single language

### ISSUE THREAD

**Issue by kercos** [facebook/duckling#414]
Hi, 

there was an issue about this opened by @Krogsager (https://github.com/facebook/duckling/issues/404). 

The suggestion by @mauricedoepke was to "comment out all other language files in the cabal file and everywhere where they are imported."  This is a rather complex and delicate procedure which is not trivia for not-advanced Haskell programmers. I've actually tried that but ended up having a lot of compilation problems and had to rollback the changes.

Also, if you manage to do that it would be hard to pull from the repository in case of changes to files that have been modified commenting out imported libraries.

My suggestion would be to set up a config variable where to specify the languages to build. I understand it make require quite an extensive refactoring of the code, but I think it would be a very useful feature and would enormously reduce the compilation time for debugging a single language.

**Comment by chessai** [comment]
@kercos Thanks for your interest in duckling!

There are several things you can do to avoid a full compilation. First, you need to understand a basic idea that affects all Haskell build tools: Haskell can be compiled (which you are probably already doing via `stack build`) or interpreted. Compilation typically produces more efficient code, at the expense of time. Interpreted Haskell takes less time to build, but is less efficient. This makes interpreted Haskell more suitable for doing things like fast rebuilds. Haskell interpreters also come with REPLs by default :)

For example, `stack ghci` will compile the project into interpreted bytecode that is faster to iterate on. A notable improvement on this is `stack ghci --no-load`, which doesn't load any of the modules of your project. To then load a module (and any modules it depends on), you can then type into the REPL `:l MyCoolModule`. You can read more about the haskell build tool `stack` here: https://docs.haskellstack.org/en/stable/ghci/

For my work on duckling, I don't use stack, but an internal tool built on top of ghci (just like stack). Though it has this same feature. If I want to test something very quickly, I will do:
```
> :l Duckling.Debug
> debug (makeLocale ES Nothing) "espero que la comida llegue antes de seis y media" [Seal Time]
...output here...
```
And if you are testing one of the test suites, you can just use [Test.Tasty](https://hackage.haskell.org/package/tasty-1.4/docs/Test-Tasty.html):
```
> :l Duckling.Time.RU.Tests
> import Test.Tasty
> defaultMain tests
...output...
```

I hope this helps!
