### ISSUE TITLE
datetime interval timespan error

### ISSUE THREAD

**Issue by 5knnbdwm** [facebook/duckling#418]
There have been issues before and all mentioned that the bug has been fixed but I am still experiencing it, in multiple ways.
Is it expected to behave like that? From other issues, I can see that it is the exact unit of the grain, but still.

input: from 7pm till 11pm
output: 19:00 - 00:00

```JSON
{
  "_text": "from 7pm til 11pm",
  "entities": {
    "datetime": [{
      "confidence": 0.96129625,
      "values": [{
        "to": {
          "value": "2019-10-12T00:00:00.000+02:00",
          "grain": "hour"
        },
        "from": {
          "value": "2019-10-11T19:00:00.000+02:00",
          "grain": "hour"
        },
        "type": "interval"
      }, {
```

**Comment by jm8985** [comment]
I'm experiencing the same issue. Have you found a workaround?

**Comment by 5knnbdwm** [comment]
Yes @jm8985 i did, tho I don't remember perfectly cuz my project changed. 
```javascript
  // Javascript
  var timeWit = '2019-10-29T19:30:00.000+00:00'
  var time1 = new Date(timeWit)
  var time2 = new Date(time1 - 3600000)
  console.log('time1: ' + time1 + '\ntime2: ' + time2);
```
time1: Tue Oct 29 2019 20:30:00 GMT+0100 (Central European Standard Time)
time2: Tue Oct 29 2019 19:30:00 GMT+0100 (Central European Standard Time)

The time zone is specified by your server, so you might have to do something with that.

**Comment by patapizza** [comment]
Duckling returns outer upper bound for intervals: https://github.com/facebook/duckling/issues/171.

**Comment by dhruvrnaik** [comment]
@patapizza  even in `interval` type, Duckling returns outer bound only when both `from` and `to` are returned. In cases where only `to` is returned, the time is still inner bound. 
Examples:-

input : deliver from 5 to 6pm
```[{'body': 'from 5 to 6pm',
  'start': 8,
  'value': {'values': [{'to': {'value': '2021-01-12T19:00:00.000+05:30',
      'grain': 'hour'},
     'from': {'value': '2021-01-12T17:00:00.000+05:30', 'grain': 'hour'},
     'type': 'interval'},
    {'to': {'value': '2021-01-13T19:00:00.000+05:30', 'grain': 'hour'},
     'from': {'value': '2021-01-13T17:00:00.000+05:30', 'grain': 'hour'},
     'type': 'interval'},
    {'to': {'value': '2021-01-14T19:00:00.000+05:30', 'grain': 'hour'},
     'from': {'value': '2021-01-14T17:00:00.000+05:30', 'grain': 'hour'},
     'type': 'interval'}],
   'to': {'value': '2021-01-12T19:00:00.000+05:30', 'grain': 'hour'},
   'from': {'value': '2021-01-12T17:00:00.000+05:30', 'grain': 'hour'},
   'type': 'interval'},
  'end': 21,
  'dim': 'time',
  'latent': False}]```
  
  input: deliver till 6pm
```
  [{'body': 'till 6pm',
  'start': 8,
  'value': {'values': [{'to': {'value': '2021-01-12T18:00:00.000+05:30',
      'grain': 'hour'},
     'type': 'interval'},
    {'to': {'value': '2021-01-13T18:00:00.000+05:30', 'grain': 'hour'},
     'type': 'interval'},
    {'to': {'value': '2021-01-14T18:00:00.000+05:30', 'grain': 'hour'},
     'type': 'interval'}],
   'to': {'value': '2021-01-12T18:00:00.000+05:30', 'grain': 'hour'},
   'type': 'interval'},
  'end': 16,
  'dim': 'time',
  'latent': False}]
```
