### ISSUE TITLE
Problem with languages that have unicode characters

### ISSUE THREAD

**Issue by Gvantsats** [facebook/duckling#420]
Duckling doesn't find 'ten' in for example 'ptenz' because ten is just a substring same happens with russian language. But in georgian '**ათი**' means **ten** and Duckling finds **10** in every word that has 'ათი' as a substring.  for example this is the answer on the text '**პათიზ**'

`[ {
        "body": "ათი",
        "start": 1,
        "value": {
            "value": 10,
            "type": "value"
        },
        "end": 4,
        "dim": "number",
        "latent": false
    }
]`

  I commented all the rules and I only left one which knows that 'ათი' is ten but I still get the same result. So I thinks it's not because of the rules could it be problem with the encoding?

**Comment by 3NFBAGDU** [comment]
Same to me!

**Comment by chessai** [comment]
closing in favour of #439
