### ISSUE TITLE
Recognizing years without preposition

### ISSUE THREAD

**Issue by llermaly** [facebook/duckling#421]
Hello, 

I'm trying to get the year from this sentence : "events 2015" , only grabs 2015 as a number.

But if I put the sentence in https://duckling.wit.ai/ grabs 2015 correctly as year.

What can I do to have this behav in my side?

Regards

**Comment by patapizza** [comment]
Hi @llermaly, Duckling returns numerals as `latent` dates.  By default, `latent` entities aren't returned. To get them, set the `withLatent` option in the function call.

https://duckling.wit.ai still needs to use the Haskell Duckling, tracked in https://github.com/wit-ai/wit/issues/1208.

**Comment by llermaly** [comment]
Thanks @patapizza  for your answer. I'm using rasa with the rasa/duckling docker image. Do you know how can I set the option or which file I have to change in duckling to activate withLatent option by default? thanks
