### ISSUE TITLE
Issue in identifying date and time using grain

### ISSUE THREAD

**Issue by anjaly** [facebook/duckling#430]
if I give '6am' I'm getting the below response

{
"_text": "6am",
"entities": {
"datetime": [
{
"confidence": 0.955325,
"values": [
{
"value": "2019-10-15T06:00:00.000-07:00",
"grain": "hour",
"type": "value"
},
{
"value": "2019-10-16T06:00:00.000-07:00",
"grain": "hour",
"type": "value"
},
{
"value": "2019-10-17T06:00:00.000-07:00",
"grain": "hour",
"type": "value"
}
],
"value": "2019-10-15T06:00:00.000-07:00",
"grain": "hour",
"type": "value"
}
]
},
"msg_id": "1xKAJKHbGIqKhw0Uh"
}

and if I give 'today at 6am' it gives the following response

{
"_text": "today at 6am",
"entities": {
"datetime": [
{
"confidence": 0.96359333333333,
"values": [
{
"value": "2019-10-14T06:00:00.000-07:00",
"grain": "hour",
"type": "value"
}
],
"value": "2019-10-14T06:00:00.000-07:00",
"grain": "hour",
"type": "value"
}
]
},
"msg_id": "1uXShfcYCm85H76pG"
}

In both cases the 'grain' have value 'hour'. Can some one provide a solution for how to check if the user has provided date or not.

**Comment by anjaly** [comment]
Hi team,
Can some one please help in fixing the issue in getting date and time separately.

**Comment by patapizza** [comment]
Hi @anjaly,

In the first case, you get 3 different datetime values as the date isn't specified. In the second case, you get a single value as there is no ambiguity around the date.

Hope this helps.
