### ISSUE TITLE
chinese input always returns wit/greetings

### ISSUE THREAD

**Issue by anjaly** [facebook/duckling#432]
HI, 
We have a wit.ai app which in is English language. We expect out AI to return no intents if we input in any other language.
But in our wit.ai app, any  input in Chinese language returns wit/greetings.
How can we fix this.

Thanks and Regards 
Anjaly

**Comment by chessai** [comment]
Hi @anjaly! Thanks for your interesting in duckling. Some questions:

1. Does this happen for languages other than ZH (Chinese). Have you tried, say, ES (Spanish) or something else?
2. Can you provide some input/output pair that demonstrates the issue you're seeing?

**Comment by chessai** [comment]
closing, please open an issue on https://github.com/wit-ai/wit
