### ISSUE TITLE
Arabic writing of Monday is not recognized ! 

### ISSUE THREAD

**Issue by hno1993** [facebook/duckling#434]
hello 

when I write "يوم الأثنين" the wit/datetime entity does not recognize it as "Monday"
but when I write "يوم الاثنين" it recognized correctly ...

I think the problem is with "ء" Al-Hamza
the remaining days are correctly recognized with Al-Hamza and without

**Comment by beshoo** [comment]
Hi, it is normal since الأثنين is not correct. The correcte one without Hamza. Which is expected behavior from wit.
