### ISSUE TITLE
How to run duckling on HTTPS (ssl) on docker? 

### ISSUE THREAD

**Issue by aditya14896** [facebook/duckling#436]
Hi, 
I am trying to run duckling server on HTTPS with ssl certs. 
Tried `stack exec duckling-example-exe -- -p 8444 --ssl-port=8444 --ssl-cert=cert.pem --ssl-key=key.pem --ssl-address=0.0.0.0` but it seems to have no effect. 

Can anyone help regarding the same asap.

**Comment by aditya14896** [comment]
@patapizza Is there any way to do that?

**Comment by aditya14896** [comment]
[SOLVED]

checkout stack.yaml at 
https://github.com/aditya14896/duckling/blob/master/stack.yaml

snap-server needs to be installed with `openssl:true` flag
By default this flag is false, hence `HsOpenssl` is not installed, which is used to start the server with ssl.

Updated the command to 
`stack exec duckling-example-exe -- -p 8080 --ssl-port=8443 --ssl-cert=cert.pem --ssl-key=key.pem --ssl-address=0.0.0.0 -no-ssl-chain-cert`

**Comment by zoobab** [comment]
I have the following error with a duckling configured in SSL:

[29/Jun/2023:14:46:36 +0000] got exception in httpAcceptFunc: ProtocolError "error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca"

Any idea which part of the code handles SSL?
