### ISSUE TITLE
State of the project and community contributions

### ISSUE THREAD

**Issue by ccoreilly** [facebook/duckling#441]
Although new commits are being pushed every week or two it seems no one is reviewing the open pull requests from the community. Could one of the maintainers shed some light? @haoxuany ? @patapizza ?

There are lots of improvements coming from the community and it'd be great to have them merged if the project is still considered active.

**Comment by patapizza** [comment]
Thanks for calling this out.

Indeed, there are a lot of great improvements and language support extensions needing some love. Sorry for the latency. I'm working on a plan to improve the support and get these merged.

**Comment by jmacedoit** [comment]
@patapizza Any news on this? We should not let let this project die or stall.

**Comment by patapizza** [comment]
Agreed, we're still working on this.

**Comment by chessai** [comment]
I am now actively maintaining duckling, with a more focused effort than possible by @patapizza et al. who are working on many other things. Expect more throughput from now on
