### ISSUE TITLE
Unable to train intent examples

### ISSUE THREAD

**Issue by anjaly** [facebook/duckling#445]
Hi,

We are using wit.ai as our chatbot AI.
I'm unable to train "increase temperature" for intent 'increase_temperature'.
The input is showing under the samples for  intent 'increase_temperature' but when we input thee text in the understanding tab the intent is not getting identified.

Can someone please help us in fixing this.

Our appId is 3235333559841650

**Comment by patapizza** [comment]
Hi @anjaly, please use https://github.com/wit-ai/wit/issues for Wit.ai issues. Thanks.
