### ISSUE TITLE
Hebrew Enhancements

### ISSUE THREAD

**Issue by idanadut** [facebook/duckling#449]
Hi Eveyone!
I just made a pull request and this is my first time contributing to Ducking (I plan to contribute more to this great project). I wanted to ask:
1) how much time approx are you able to review and merge the changes to the project? WILL IT BE POSSIBLE to merge in the upcoming days/this week? (not to be rude I'm just eager to see deploy impact on my wit.ai project:)
2) If it is merged, is it automatically updated in wit.ai as well?

Thanks,
Idan

This is the pull request:
"Enhancement & Fixes for Hebrew Language - Duration+TimeGrain+Time+Amount":

Description:
Handled preposition, hebrew plural forms, grammer miseaks and added support for new cases that are different from the "english language format" that some of the rules had to the correct Hebrew form.
Mostly these enhancement are about new hebrew grammer options to write time intervals, catch simple times correcly, and handle more complex forms.
All changes were tested carefully and extensively to verify all cases (and some tests added to corpus) -> 
examples:
Phrases such as "ב15 לחודש" (which mean "on the 15th of this month"), "שנה שעברה" (which means "last year"), "לפני שלושה חודשים" (which means "three months ago"), "חצי שנה אחרונה" ("past half a year"), "בין 15 לנובמבר לבין 18 לדצמבר" ("between 15th of November to 18th of December")  - will now work correctly!

**Comment by chessai** [comment]
Hi @idanadut, thanks for your contribution!

I am now maintaining this project from Facebook internally (managing external contributions as well) as a focused effort. So, expect more throughput from now on.

To answer your question about wit, changes merged to duckling do not take place in wit automatically, the changes need to be deployed to wit by hand (i.e. there is no CD for duckling wrt wit). But, this process of deploying is trivial, so once your change lands, getting wit up to date could happen fairly shortly after.

Hope this clears things up! Thanks
