### ISSUE TITLE
prediction time afternoon or not

### ISSUE THREAD

**Issue by spotlight2001** [facebook/duckling#450]
hi, 

in german: "ich hätt gern einen termin um viertel vor 3"
in english: "i would like an appointment quarter before 3"

The user has in my domain implicit expectations due to opening hours.
Can I somehow hint duckling to pick afternoon in this case?
Without forcing the end user to use "afternoon" explicitly

**Comment by chessai** [comment]
Duckling already picks afternoon in this case.

**Comment by spotlight2001** [comment]
in this given case it works. there are similar cases where it doesnt:

![2021-04-13 07_22_41-Window](https://user-images.githubusercontent.com/5476424/114500856-32837400-9c29-11eb-82b4-e33aff6a901f.png)

due to opening hours a user would expect: 14:50
duckling picks: 2:50 which is technically correct

**Comment by chessai** [comment]
Sure! Open a new issue. Thanks!
