### ISSUE TITLE
Number in text not identifying

### ISSUE THREAD

**Issue by anjaly** [facebook/duckling#453]
Hi,

The number in text like one, two, three etc are not returning entity number/ordinal.
 Is there any solution for identiying them.
I tried to train them in wit.ai but still it is not getting the entity. Kindly advice.

Thanks 
Anjaly

**Comment by SuunnyyGoo** [comment]
Hi, 

Same for me, all numbers are caught as amount-of-money, even with no currency after the figure, neither training data.

Thanks

**Comment by chessai** [comment]
Hi @anjaly, @SuunnyyGoo, could you provide an example of input and output where duckling is doing the wrong thing?

**Comment by chessai** [comment]
From the debug output:

```
> debug (makeLocale EN Nothing) "one" [Seal Numeral]
integer (0..19) (one)
-- regex (one)
[Entity {dim = "number", body = "one", value = RVal Numeral (NumeralValue {vValue = 1.0}), start = 0, end = 3, latent = False, enode = Node {nodeRange = Range 0 3, token = Token Numeral (NumeralData {value = 1.0, grain = Nothing, multipliable = False, okForAnyTime = True}), children = [Node {nodeRange = Range 0 3, token = Token RegexMatch (GroupMatch ["one","","","",""]), children = [], rule = Nothing}], rule = Just "integer (0..19)"}}]
```

If you are using the executable, are you supplying the dimensions in the query parameter? e.g.
`$ curl -XPOST http://0.0.0.0:8000/parse --data 'locale=en_GB&dims=number&text=one'`

**Comment by chessai** [comment]
Closing as a non-issue, since I feel the crux of the matter is not setting the dimensions.

Please let me know if you feel otherwise by re-opening.
