### ISSUE TITLE
Wrong intent

### ISSUE THREAD

**Issue by anjaly** [facebook/duckling#454]
Hi team,

We are using wit.ai for our chatbot.
Our appId is 3235333559841650
Our issue is that "what's the special offer today" is identifying greeting intent where as "what's the special offer" identifies no intent.
Also "what's the temperature of my room" returns "get_temperature" but "what's the temperature of my" doesn't.
Actually we don't expect any intent for  "what's the special offer today".
Can you please help us in identifying if there is any issue in the process that we are training inputs.
Also please let us know why it behave in different ways even though it don't have any words trained in that intent.

Thanks,
Anjaly

**Comment by amtdevops** [comment]
Hi,
Any update please

**Comment by patapizza** [comment]
Hi, this isn't related to Duckling. Let's follow https://github.com/wit-ai/wit/issues/1659 for tracking this. Thanks.
