### ISSUE TITLE
Public Changelog

### ISSUE THREAD

**Issue by LucasLLC** [facebook/duckling#455]
From the releases tab, I can only see changelog entries up to `v0.1.6.1`, which was created around two years ago. There's already an issue here asking why there hasn't been releases: https://github.com/facebook/duckling/issues/328 .

I'm currently trying to decide on whether or not to upgrade duckling from `v0.1.6.1` to the latest branch, but it's difficult to go through two years of changes without a changelog. Would it be possible to make the changelog public on the repo, so we can see changes made to duckling on latest?

Thanks

**Comment by chessai** [comment]
There is currently no good changelog. I need to go through the backlog of commits and compile one. Once it has been compiled, changelog entries should be mandatory for all commits.
