### ISSUE TITLE
Build Fail

### ISSUE THREAD

**Issue by YanivHakim** [facebook/duckling#458]
Hi,

I try to build the last version of the lib with stack and always get this message at the end.
I tried both on Ubuntu and windows.

> Warning: The following modules should be added to exposed-modules or other-modules in C:\Projects\duckling\duckling\duckling.cabal:
>              - In lib:
>                  Duckling.Numeral.ES.AR.Rules
>                  Duckling.Numeral.ES.CL.Rules
>                  Duckling.Numeral.ES.CO.Rules
>                  Duckling.Numeral.ES.ES.Rules
>                  Duckling.Numeral.ES.MX.Rules
>                  Duckling.Numeral.ES.PE.Rules
>                  Duckling.Numeral.ES.VE.Rules
>              - In lib:
>                  Duckling.Numeral.ES.AR.Rules
>                  Duckling.Numeral.ES.CL.Rules
>                  Duckling.Numeral.ES.CO.Rules
>                  Duckling.Numeral.ES.ES.Rules
>                  Duckling.Numeral.ES.MX.Rules
>                  Duckling.Numeral.ES.PE.Rules
>                  Duckling.Numeral.ES.VE.Rules
>              - In lib:
>                  Duckling.Numeral.ES.AR.Rules
>                  Duckling.Numeral.ES.CL.Rules
>                  Duckling.Numeral.ES.CO.Rules
>                  Duckling.Numeral.ES.ES.Rules
>                  Duckling.Numeral.ES.MX.Rules
>                  Duckling.Numeral.ES.PE.Rules
>                  Duckling.Numeral.ES.VE.Rules
>              - In lib:
>                  Duckling.Numeral.ES.AR.Rules
>                  Duckling.Numeral.ES.CL.Rules
>                  Duckling.Numeral.ES.CO.Rules
>                  Duckling.Numeral.ES.ES.Rules
>                  Duckling.Numeral.ES.MX.Rules
>                  Duckling.Numeral.ES.PE.Rules
>                  Duckling.Numeral.ES.VE.Rules
>              - In lib:
>                  Duckling.Numeral.ES.AR.Rules
>                  Duckling.Numeral.ES.CL.Rules
>                  Duckling.Numeral.ES.CO.Rules
>                  Duckling.Numeral.ES.ES.Rules
>                  Duckling.Numeral.ES.MX.Rules
>                  Duckling.Numeral.ES.PE.Rules
>                  Duckling.Numeral.ES.VE.Rules
>              - In lib:
>                  Duckling.Numeral.ES.AR.Rules
>                  Duckling.Numeral.ES.CL.Rules
>                  Duckling.Numeral.ES.CO.Rules
>                  Duckling.Numeral.ES.ES.Rules
>                  Duckling.Numeral.ES.MX.Rules
>                  Duckling.Numeral.ES.PE.Rules
>                  Duckling.Numeral.ES.VE.Rules
> 
>          Missing modules in the cabal file are likely to cause undefined reference errors from the linker, along with other problems.
> Completed 66 action(s).
> 
> --  While building package duckling-0.1.6.1 using:
>       C:\sr\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_1.24.2.0_ghc-8.0.2.exe --builddir=.stack-work\dist\ca59d0ab build lib:duckling exe:custom-dimension-example exe:duckling-example-exe exe:duckling-expensive exe:duckling-regen-exe exe:duckling-request-sample --ghc-options ""
>     Process exited with code: ExitFailure 1

Any ideas??

**Comment by patapizza** [comment]
Thanks for reporting! Looks like we forgot to update `duckling.cabal` in https://github.com/facebook/duckling/commit/0527be1ce02ff09a6592b9d640ebd653ffe3f558. Sorry about that, we'll fix that.

**Comment by YanivHakim** [comment]
Thanks! waiting for your update
