### ISSUE TITLE
stack build failed

### ISSUE THREAD

**Issue by EdukondaluK** [facebook/duckling#466]
have cloned repo and doing stack build.
am getting an below error. access denied , it has tested with admin rights too.

![image](https://user-images.githubusercontent.com/18613739/77722190-09d70f00-7013-11ea-85fd-9d058cba14e8.png)

thanks and Regards,
Edukondalu
+91 6303074590

**Comment by chessai** [comment]
Definitely a `stack` issue, not a duckling issue. See https://github.com/commercialhaskell/stack/issues/1917
