### ISSUE TITLE
Detecting wrong built-in entity

### ISSUE THREAD

**Issue by anjaly** [facebook/duckling#469]
Hi team,
Our appid is 1530202523770626
We have some examples trained in wit/greetings which have the keyword "good" in it.
The issue occurred when we input "Goodbye" it detected wit/greetings and showed wrong response.
We tried to retrain but it didn't work.
How should we handle this.
Please advice

Regards
Anjaly

**Comment by patapizza** [comment]
Hi @anjaly, please use https://github.com/wit-ai/wit/issues for Wit.ai issues. Thanks.
