### ISSUE TITLE
Wrong detection of datetime instead of duration in polish language

### ISSUE THREAD

**Issue by galubap** [facebook/duckling#492]
In my app sentence (in polish) "ustaw minutnik na 15 minut" (english translation: "set the timer to 15 minutes") doesn't work, because "15 minutes" is detected as datetime "9.06.2020, 15:00:00". This is completly wrong understanding of polish language.
Sentences like: "5 minut", "5 godzin", "5 sekund" (english exact translation: "5 minutes", "5 hours", "5 seconds"), are not datetime. They are duration. Datetime is e.g "godzina 5", "godzina 3:45".
App id: 3382588755148772

**Comment by patapizza** [comment]
See my comment in https://github.com/wit-ai/wit/issues/1796.

**Comment by galubap** [comment]
I gave you detailed description why it's not correct. Did you even read my post? Or maybe, your knowledge of polish language is better than my
 
 
 
See my comment in wit-ai/wit#1796.
