### ISSUE TITLE
[Vietnamese(VI) Error in Amount of money]

### ISSUE THREAD

**Issue by Vietdung113** [facebook/duckling#511]
I have used duckling for extract information of amount of money. 
Everything work well in my local computer(out of docker) but when i pushed it to docker and build it. Duckling can't extract information of amount of money as same as duckling in my computer(out of docker). 
I tried to run 
```stack build :duckling-regen-exe ```
But got error 
```duckling-0.1.6.1: unregistering (local file changes: Duckling/Ranking/Classifiers/AR_XX.hs)
duckling> configure (lib + exe)
Configuring duckling-0.1.6.1...
duckling> build (lib + exe)
Preprocessing library duckling-0.1.6.1...

/home/chatbot/duckling/Duckling/Ranking/Classifiers/AR_XX.hs:1:1: error:
    File name does not match module name:
    Saw: `Main'
    Expected: `Duckling.Ranking.Classifiers.AR_XX'

--  While building package duckling-0.1.6.1 using:
      /root/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.2.0 build lib:duckling exe:duckling-regen-exe --ghc-options ""
    Process exited with code: ExitFailure 1
```
Anyone can help me.
T.y

**Comment by chessai** [comment]
Just reading this issue. Has nothing to do with vietnamese or parsing, you're getting a build error. It looks like you or a tool removed a module name somehow? Anyway, this should be fixed in `master`. I can't replicate it. Please re-open if you're still experiencing the issue.
