### ISSUE TITLE
Support for abbreviation of Indian Currency

### ISSUE THREAD

**Issue by avNextLeap** [facebook/duckling#519]
I started using duckling for the 'money' entity extraction. But found that Indian Currency abbreviation are not supported.
Example -- 
1 Crore .. can we written as 1 Cr.  
1 lakh -- can be written as 1L or 1lkh

So any plans to add it.. or any help in how i can extend the duckling to support such abbreviation

**Comment by chessai** [comment]
Done in 181037e469991effe01ba764135792ec1c4e31b8
