### ISSUE TITLE
Latent

### ISSUE THREAD

**Issue by christopher5106** [facebook/duckling#521]
Hi,
I don't understand the meaning of the latent field in the results, and do not find any example request where the result has a latent positioned to True.
Could you please give further details ?
Best,

**Comment by chinmay87** [comment]
Latent entities are entities that, on their own, do not have sufficient information to conclude that it belongs to a dimension.
Eg: 
* "for 9" - could be "for 9am" or "for 9 people"? 
* "may" - could be the month or the auxiliary verb

To detect latent entities, set `withLatent` to `True` in the `Options`
This can be used in cases where one has a high confidence that the input is of a particular dimension.

**Comment by christopher5106** [comment]
Thanks!
