### ISSUE TITLE
exhaustive list of all possible return types

### ISSUE THREAD

**Issue by franklevasseur** [facebook/duckling#537]
Hi,

Is there an exhaustive list of all possible return types of Duckling? I'm currently building a Typescript wrapper around Duckling (I'll probably publish it on npm), but I'm not sure what possible datastructures can be returned by duckling...

For example, if a time is extracted, if `type == 'value'` then I expect properties `value` and `grain`. If `type == 'interval'`, I expect properties `from` and `two`, each of them having `value` and `grain`. I also noticed, a time can have property `values` an array of the previous types. For a `type == 'value'`, is it possible to have `values` defined, but no root `value` or `grain` ?

This example is only one of many questions I have regarding the returned data-structure of Duckling.

Is there any documentation to help me out?

Right now, my typings looks like this:

<details>
  <summary>typings</summary>

```ts
type Duckling = DucklingReturn<DucklingDimension>

interface DucklingReturn<D extends DucklingDimension> {
  start: number
  end: number
  dim: D
  body: string
  value: DucklingValue<D, DucklingType>
}

type DucklingDimension =
  | 'amountOfMoney'
  | 'distance'
  | 'duration'
  | 'email'
  | 'number'
  | 'ordinal'
  | 'phoneNumber'
  | 'quantity'
  | 'temperature'
  | 'time'
  | 'url'
  | 'volume'

type DucklingType = 'value' | 'interval'

type DucklingValue<D extends DucklingDimension, T extends DucklingType> = {
  type: T
} & (D extends 'duration' ? { normalized: ValueUnit } : D extends 'time' ? DucklingTimeValue<T> : ValueUnit)

type DucklingTimeValue<T extends DucklingType> = T extends 'interval'
  ? TimeInterval & { values?: TimeInterval[] }
  : ValueGrain & { values?: ValueGrain[] }

interface ValueUnit {
  value: string
  unit: string
}

interface ValueGrain {
  value: string
  grain: string
}

interface TimeInterval {
  from: ValueGrain
  to: ValueGrain
}

// duckling type guards
const _isDuration = (duck: Duckling): duck is DucklingReturn<'duration'> => {
  return duck.dim === 'duration'
}

const _isTime = (duck: Duckling): duck is DucklingReturn<'time'> => {
  return duck.dim === 'time'
}

const _isTimeInterval = (
  duckTime: DucklingValue<'time', DucklingType>
): duckTime is DucklingValue<'time', 'interval'> => {
  return duckTime.type === 'interval'
}

const _isTimeValue = (duckTime: DucklingValue<'time', DucklingType>): duckTime is DucklingValue<'time', 'value'> => {
  return duckTime.type === 'value'
}
```
</details>

**Comment by chessai** [comment]
hi @franklevasseur! Is your typescript wrapper public? I'd love to see it, and possibly link to it in the docs!

Currently there is no exhaustive list of all return types, but it would be great to have one typed out.

**Comment by franklevasseur** [comment]
Hi @chessai,

Everything I have have that relates to duckling so far is located [here](https://github.com/botpress/botpress/blob/master/src/bp/nlu-core/entities/duckling-extractor/typings.ts). It's part of the [botpress](https://github.com/botpress/botpress) source code. I don't think these typings covers all possible duckling datastructure format, but its a start.

I also have these typeguards (located [here](https://github.com/botpress/botpress/blob/master/src/bp/nlu-core/entities/duckling-extractor/map-duckling.ts)) that I use in the code to better identify the duckling DS format at runtime:

```ts
const _isDuration = (duck: Duckling): duck is DucklingReturn<'duration'> => {
  return duck.dim === 'duration'
}

const _isTime = (duck: Duckling): duck is DucklingReturn<'time'> => {
  return duck.dim === 'time'
}

const _isTimeInterval = (
  duckTime: DucklingValue<'time', DucklingType>
): duckTime is DucklingValue<'time', 'interval'> => {
  return duckTime.type === 'interval'
}

const _isTimeValue = (duckTime: DucklingValue<'time', DucklingType>): duckTime is DucklingValue<'time', 'value'> => {
  return duckTime.type === 'value'
}

const _isValueUnit = (
  duckValue: DucklingValue<DucklingDimension, DucklingType>
): duckValue is { type: DucklingType } & ValueUnit => {
  return _isValue(duckValue) && !!(duckValue as ValueUnit).unit
}

const _isValue = (
  duckValue: DucklingValue<DucklingDimension, DucklingType>
): duckValue is { type: DucklingType } & Value => {
  return _.isNumber((duckValue as Value).value) || !!(duckValue as Value).value
}
```

Do you see anything missing? 

What I plan to do is create a Typescript wrapper for the duckling and make it an npm package. The package would contain an http client, typings and typeguards. If I do make this, I'd sure be very happy that you link the repo in your documentation. However, for now, I just don't want to make a package out of something so incomplete.

What do you think?

François
