### ISSUE TITLE
Unable to get next week dates for Spanish texts

### ISSUE THREAD

**Issue by muzam** [facebook/duckling#553]
I would like to get coming Monday to next Monday dates. I am able to do that for English text by using `next 1 week` but for Spanish, I am not able to do it.

I had tried the following texts
`la semana que viene`
`el próximo lunes a domingo`
`la próxima semana`

**Comment by chessai** [comment]
@muzam looks like there is no rules for this in ES. Would you like to PR them?

**Comment by chessai** [comment]
This is actually already supported. Closing
