### ISSUE TITLE
Error when testing new language CA

### ISSUE THREAD

**Issue by leandroPGC** [facebook/duckling#557]
Hi, 
we are adding Catalan language to Duckling and we have succesfully compiled it. However, test stage fails due to "empty result on" error on some of the examples of the corpus, for example:

```
Volume Tests
    AR Tests
        Corpus Tests:              OK
    CA Tests
       Corpus Tests:              FAIL
          empty result on "250 mililitres"
```

Any idea what might be happening?

Thanks in advance

**Comment by chessai** [comment]
Hi @leandroPGC, thanks for your work! A few questions:

1. Could you put the PR up? Hard to tell anything without any code.
2. Have you checked that your regex is correct, or that there is indeed a rule that you expect to capture `"250 mililitres"`?
3. Have you checked your production?

All of this would be easier for me to determine/help with if I could see code, but I cannot unfortunately

**Comment by leandroPGC** [comment]
Hi @chessai, thanks for your fast reply. 
Sorry for not raising the issue with the code. Thought might be a common error with quick solution. 

My answers to your questions:

1. I have opened a [pull request](https://github.com/facebook/duckling/pull/558/commits) you asked.
2. Yes to both of your questions. We have checked the regex and we took as reference Spanish language, that has the same rule.
3. I'm not sure what do you mean with that.

**Comment by chessai** [comment]
Closing since this discussion should happen in the PR
