### ISSUE TITLE
Dimension CreditCardNumber is not yet detected

### ISSUE THREAD

**Issue by jpslopes** [facebook/duckling#562]
Hello,

I tested the new version of Duckling (built Docker image locally) and noticed that it still does not detect credit card numbers. So, taking into account the following reply https://github.com/facebook/duckling/issues/551#issuecomment-737645140:

> Looks like there are no rules for this in EN.
>
>    EDIT: CreditCardNumber is in the common rules, so should be present regardless of locale.
>
>    How are you invoking duckling?

I looked up in Dimensions/Common.hs and noticed that `CreditCardNumber` is not present there. I tried adding it to the list of common dimensions and it worked like a charm.
```haskell
allDimensions :: [Seal Dimension]
allDimensions =
  [ Seal AmountOfMoney
  , Seal CreditCardNumber
  , Seal Email
  , Seal Numeral
  , Seal PhoneNumber
  , Seal Url
  ]
```
When sending a request with the following input (without passing the parameter `dims`):
- text: "4111-1111-1111-1111"
- locale: "en_US"

The response was the following:
```json
[
    {
        "body": "4111-1111-1111-1111",
        "start": 0,
        "value": {
            "value": "4111111111111111",
            "issuer": "visa"
        },
        "end": 19,
        "dim": "credit-card-number",
        "latent": false
    },
    {
        "body": "4111-1111-1111-1111",
        "start": 0,
        "value": {
            "value": "4111111111111111",
            "type": "value"
        },
        "end": 19,
        "dim": "phone-number",
        "latent": false
    }
]
```
And tried sending a credit card number without dashes (also without passing the parameter `dims`):
- text: "4111111111111111"
- locale: "en_US"

The response was the following:
```json
[
    {
        "body": "4111111111111111",
        "start": 0,
        "value": {
            "value": "4111111111111111",
            "issuer": "visa"
        },
        "end": 16,
        "dim": "credit-card-number",
        "latent": false
    },
    {
        "body": "4111111111111111",
        "start": 0,
        "value": {
            "value": "4111111111111111",
            "type": "value"
        },
        "end": 16,
        "dim": "phone-number",
        "latent": false
    },
    {
        "body": "4111111111111111",
        "start": 0,
        "value": {
            "value": 4111111111111111,
            "type": "value"
        },
        "end": 16,
        "dim": "number",
        "latent": false
    }
]
```

Thanks

**Comment by chessai** [comment]
resolved in master, thanks for reporting
