### ISSUE TITLE
Inconsistencies in returned time intervals

### ISSUE THREAD

**Issue by dhruvrnaik** [facebook/duckling#568]
@patapizza  even in `interval` type, Duckling returns outer bound only when both `from` and `to` are returned. In cases where only `to` is returned, the time is still inner bound. 
Examples:-

input : deliver from 5 to 6pm
value.to : 2021-01-12T19:00:00.000+05:30
```
[{'body': 'from 5 to 6pm',
  'start': 8,
  'value': {'values': [{'to': {'value': '2021-01-12T19:00:00.000+05:30',
      'grain': 'hour'},
     'from': {'value': '2021-01-12T17:00:00.000+05:30', 'grain': 'hour'},
     'type': 'interval'},
    {'to': {'value': '2021-01-13T19:00:00.000+05:30', 'grain': 'hour'},
     'from': {'value': '2021-01-13T17:00:00.000+05:30', 'grain': 'hour'},
     'type': 'interval'},
    {'to': {'value': '2021-01-14T19:00:00.000+05:30', 'grain': 'hour'},
     'from': {'value': '2021-01-14T17:00:00.000+05:30', 'grain': 'hour'},
     'type': 'interval'}],
   'to': {'value': '2021-01-12T19:00:00.000+05:30', 'grain': 'hour'},
   'from': {'value': '2021-01-12T17:00:00.000+05:30', 'grain': 'hour'},
   'type': 'interval'},
  'end': 21,
  'dim': 'time',
  'latent': False}]
```
  
  input: deliver till 6pm
  value.to : 2021-01-12T18:00:00.000+05:30
```
  [{'body': 'till 6pm',
  'start': 8,
  'value': {'values': [{'to': {'value': '2021-01-12T18:00:00.000+05:30',
      'grain': 'hour'},
     'type': 'interval'},
    {'to': {'value': '2021-01-13T18:00:00.000+05:30', 'grain': 'hour'},
     'type': 'interval'},
    {'to': {'value': '2021-01-14T18:00:00.000+05:30', 'grain': 'hour'},
     'type': 'interval'}],
   'to': {'value': '2021-01-12T18:00:00.000+05:30', 'grain': 'hour'},
   'type': 'interval'},
  'end': 16,
  'dim': 'time',
  'latent': False}]
```

Is there a specific reason for this behavior? 
Would be much better to keep it consistent (preferably inner bound) across all time interval outputs.

_Originally posted by @dhruvrnaik in https://github.com/facebook/duckling/issues/418#issuecomment-758555131_

**Comment by dhruvrnaik** [comment]
Just found another problem, hence created a separate issue.

input: deliver by 6pm
```
[{'body': 'by 6pm',
  'start': 8,
  'value': {'values': [{'to': {'value': '2021-01-12T18:00:00.000+05:30',
      'grain': 'second'},
     'from': {'value': '2021-01-12T15:53:59.970+05:30', 'grain': 'second'},
     'type': 'interval'}],
   'to': {'value': '2021-01-12T18:00:00.000+05:30', 'grain': 'second'},
   'from': {'value': '2021-01-12T15:53:59.970+05:30', 'grain': 'second'},
   'type': 'interval'},
  'end': 14,
  'dim': 'time',
  'latent': False}]
```
Here the outputs are
from: 2021-01-12T15:53:59.970+05:30 (_current time_)
to: 2021-01-12T18:00:00.000+05:30

This is inconsistent with my earlier assumption that upper bound applied when both `from` and `to` are returned, creating further confusion and difficulty in parsing the outputs.

**Comment by chessai** [comment]
"till <time>" and "by <time>" are upper-exclusive in <time>. "<time> to <time>" is inclusive in both times. This is the reasoning for this behaviour.
