### ISSUE TITLE
Strange quantity/volume entities are extracted from Arabic subtokens

### ISSUE THREAD

**Issue by AMR-K** [facebook/duckling#571]
The `جم`(`gram` in English) prefix  gets extracted from the word `جمبري` (`shrimps` in English).
I think adding `\b` around the regexps would be enough for this case but I don't how to do this tweak in Haskell.
For example: 
The regex in https://github.com/facebook/duckling/blob/ff4a1a5baeb3fa826edbda8bd8b1f7030d469b0a/Duckling/Quantity/AR/Rules.hs#L115-L126
should be changed to `\b` +  regexPattern + `\b`.
Could you please tell me how to write this regexp in Haskell?

This issue looks similar to #437

**Comment by chessai** [comment]
@AMR-K so the type of `regex` is `regex :: String -> PatternItem`, ie it takes a String representing a regex and turns it into something duckling can use to extract patterns. first, note function application in haskell is denoted by spaces, so in eg JS, you would say `f(x)`, but in haskell you say `f x`. so all you need to do to append is intead of `regex regexPattern`, you would write `regex ("\b" ++ regexPattern ++ "\b")`. You could go ahead and give this a try and run the tests locally or wait for CI. If you need any help let me know.

**Comment by AMR-K** [comment]
@chessai Adding "\b" is working given the current configuration of Duckling. I have checked this page (https://wiki.haskell.org/Regular_expressions#regex-pcre) and I think it should be supported in the `regex-pcre` library.
Do you know how to find whether the Arabic regex is based on the basic regex library or the `regex-pcre` one?

OTOH, I wonder why isn't `six` extracted as a numeral from `sixers` in English Numeral Dimension for example. It's exactly the same case and I don't see anything special about the regex used there:
https://github.com/facebook/duckling/blob/590651150bd51d69dd9f73872b3a869e0842fd97/Duckling/Numeral/EN/Rules.hs#L70-L101
Is there any checks that are done on the matched value in the English regexp?

**Comment by chessai** [comment]
> @chessai Adding "\b" is working given the current configuration of Duckling. I have checked this page (https://wiki.haskell.org/Regular_expressions#regex-pcre) and I think it should be supported in the `regex-pcre` library.
> Do you know how to find whether the Arabic regex is based on the basic regex library or the `regex-pcre` one?
>

regex-pcre is the only regex library used by duckling.
Also, do you have a PR? I have a hunch it won't pass all tests, but I would be excited to be wrong.

> OTOH, I wonder why isn't `six` extracted as a numeral from `sixers` in English Numeral Dimension for example. It's exactly the same case and I don't see anything special about the regex used there:
> https://github.com/facebook/duckling/blob/590651150bd51d69dd9f73872b3a869e0842fd97/Duckling/Numeral/EN/Rules.hs#L70-L101
> Is there any checks that are done on the matched value in the English regexp?
> 

Duckling does some "magic" (read: big hack) to detect word boundaries within regex matches. So duckling is able to tell that "sixers" should not resolve to the numeral 6, even though the regex matched. Duckling's logic works well for English, romance languages, etc, but for things like Arabic, Chinese, etc. it has a harder time detecting proper word boundaries. There are a few open bugs due to this.

**Comment by AMR-K** [comment]
> > @chessai Adding "\b" is working given the current configuration of Duckling. I have checked this page (https://wiki.haskell.org/Regular_expressions#regex-pcre) and I think it should be supported in the `regex-pcre` library.
> > Do you know how to find whether the Arabic regex is based on the basic regex library or the `regex-pcre` one?
> 
> regex-pcre is the only regex library used by duckling.
> Also, do you have a PR? I have a hunch it won't pass all tests, but I would be excited to be wrong.
> 
Opps, my bad.
Actually, it **isn't** working. I tried the unescaped version "\b" and the escaped one "\\b" but they didn't work. That's why I thought that the `regex-pcre` library isn't used by default in Arabic.
Is there a way to test a regex on its own outside duckling and check if it should do the job or not? I looked for websites online but none of them supported Haskell regexps.

> > OTOH, I wonder why isn't `six` extracted as a numeral from `sixers` in English Numeral Dimension for example. It's exactly the same case and I don't see anything special about the regex used there:
> > https://github.com/facebook/duckling/blob/590651150bd51d69dd9f73872b3a869e0842fd97/Duckling/Numeral/EN/Rules.hs#L70-L101
> > 
> > Is there any checks that are done on the matched value in the English regexp?
> 
> Duckling does some "magic" (read: big hack) to detect word boundaries within regex matches. So duckling is able to tell that "sixers" should not resolve to the numeral 6, even though the regex matched. Duckling's logic works well for English, romance languages, etc, but for things like Arabic, Chinese, etc. it has a harder time detecting proper word boundaries. There are a few open bugs due to this.
Hmmmm.
Can you send me pointers to how/where the magic is implemented 😄 ?

**Comment by chessai** [comment]
> > > @chessai Adding "\b" is working given the current configuration of Duckling. I have checked this page (https://wiki.haskell.org/Regular_expressions#regex-pcre) and I think it should be supported in the `regex-pcre` library.
> > > Do you know how to find whether the Arabic regex is based on the basic regex library or the `regex-pcre` one?
> > 
> > regex-pcre is the only regex library used by duckling.
> > Also, do you have a PR? I have a hunch it won't pass all tests, but I would be excited to be wrong.
> > 
> Opps, my bad.
> Actually, it **isn't** working. I tried the unescaped version "\b" and the escaped one "\\\\b" but they didn't work. That's why I thought that the `regex-pcre` library isn't used by default in Arabic.
> Is there a way to test a regex on its own outside duckling and check if it should do the job or not? I looked for websites online but none of them supported Haskell regexps.
>

Sure, load up `cabal repl` and `:l Text.Regex.PCRE.ByteString`. the module docs are here: https://hackage.haskell.org/package/regex-pcre-0.95.0.0/docs/Text-Regex-PCRE-ByteString.html

> > Duckling does some "magic" (read: big hack) to detect word boundaries within regex matches. So duckling is able to tell that "sixers" should not resolve to the numeral 6, even though the regex matched. Duckling's logic works well for English, romance languages, etc, but for things like Arabic, Chinese, etc. it has a harder time detecting proper word boundaries. There are a few open bugs due to this.
> 
> Hmmmm.
> Can you send me pointers to how/where the magic is implemented 😄 ?

Yes, I am AFK right now, but look for 'charClass' in the code. The function is `isRangeValid`.

**Comment by AMR-K** [comment]
Hi @chessai 
I found that changing line 126 such that not only lower and upper case characters are having the same type `c` but also any alpha character solves the issue for Arabic.
i.e:
Change `| Char.isLower c || Char.isUpper c = 'c'` to `| Char.isAlpha c= 'c'`.
As far as I can think, this change shouldn't break any of the Arabic rules but it won't work for languages like Chinese where characters aren't separated with white-spaces.
What do you think of this?
Or should we just add a new function that checks if a character is an Arabic one of not?
(e.g.:
```
isArabic :: Char -> Bool
isArabic c = CHECK IF C IS ONE OF A LIST OF ARABIC CHARACTERS
```
)

https://github.com/facebook/duckling/blob/f68ebf808ac2df4453773dbe3a73ec847946bc5e/Duckling/Types/Document.hs#L117-L130

**Comment by chessai** [comment]
> Hi @chessai
> I found that changing line 126 such that not only lower and upper case characters are having the same type `c` but also any alpha character solves the issue for Arabic.
> i.e:
> Change `| Char.isLower c || Char.isUpper c = 'c'` to `| Char.isAlpha c= 'c'`.
> As far as I can think, this change shouldn't break any of the Arabic rules but it won't work for languages like Chinese where characters aren't separated with white-spaces.
> What do you think of this?
> Or should we just add a new function that checks if a character is an Arabic one of not?
> (e.g.:
> 
> ```
> isArabic :: Char -> Bool
> isArabic c = CHECK IF C IS ONE OF A LIST OF ARABIC CHARACTERS
> ```
> 
> UPDATE: This hack breaks only 6 Arabic tests and isn't affecting other languages.
> Moreover, I think that the failing cases can be fixed by updating some regexps.
> Can you please help me doing this? I believe that the current False Positives are really annoying.
> )
> 
> https://github.com/facebook/duckling/blob/f68ebf808ac2df4453773dbe3a73ec847946bc5e/Duckling/Types/Document.hs#L117-L130

Thanks for your continued interest in this. Would you mind putting up a PR so I can look at code?
