### ISSUE TITLE
build  failure on centos 7

### ISSUE THREAD

**Issue by hegerard** [facebook/duckling#583]
On the first "stack build" on CentOS Linux release 7.6.181 install exits on failure : 

Cabal                > [220 of 220] Compiling Distribution.Simple
Cabal                > copy/register
Cabal                > Installing library in /root/.stack/snapshots/x86_64-linux/51f16aaa57b14cd75dc90e8ab2b3d715af3e78a40b0ae80a10c32dd23d781233/8.6.5/lib/x86_64-linux-ghc-8.6.5/Cabal-2.4.1.0-3JC906oWQ73Ah7bYkIcI4J
Cabal                > Registering library for Cabal-2.4.1.0..
Progress 29/63

--  While building package regex-pcre-0.94.4 (scroll up to its section to see the error) using:
      /root/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.4.0.1 configure --user --package-db=clear --package-db=global --package-db=/root/.stack/snapshots/x86_64-linux/51f16aaa57b14cd75dc90e8ab2b3d715af3e78a40b0ae80a10c32dd23d781233/8.6.5/pkgdb --libdir=/root/.stack/snapshots/x86_64-linux/51f16aaa57b14cd75dc90e8ab2b3d715af3e78a40b0ae80a10c32dd23d781233/8.6.5/lib --bindir=/root/.stack/snapshots/x86_64-linux/51f16aaa57b14cd75dc90e8ab2b3d715af3e78a40b0ae80a10c32dd23d781233/8.6.5/bin --datadir=/root/.stack/snapshots/x86_64-linux/51f16aaa57b14cd75dc90e8ab2b3d715af3e78a40b0ae80a10c32dd23d781233/8.6.5/share --libexecdir=/root/.stack/snapshots/x86_64-linux/51f16aaa57b14cd75dc90e8ab2b3d715af3e78a40b0ae80a10c32dd23d781233/8.6.5/libexec --sysconfdir=/root/.stack/snapshots/x86_64-linux/51f16aaa57b14cd75dc90e8ab2b3d715af3e78a40b0ae80a10c32dd23d781233/8.6.5/etc --docdir=/root/.stack/snapshots/x86_64-linux/51f16aaa57b14cd75dc90e8ab2b3d715af3e78a40b0ae80a10c32dd23d781233/8.6.5/doc/regex-pcre-0.94.4 --htmldir=/root/.stack/snapshots/x86_64-linux/51f16aaa57b14cd75dc90e8ab2b3d715af3e78a40b0ae80a10c32dd23d781233/8.6.5/doc/regex-pcre-0.94.4 --haddockdir=/root/.stack/snapshots/x86_64-linux/51f16aaa57b14cd75dc90e8ab2b3d715af3e78a40b0ae80a10c32dd23d781233/8.6.5/doc/regex-pcre-0.94.4 --dependency=array=array-0.5.3.0 --dependency=base=base-4.12.0.0 --dependency=bytestring=bytestring-0.10.8.2 --dependency=containers=containers-0.6.0.1 --dependency=regex-base=regex-base-0.93.2-6BO9nGUPmsrJWZAlHnRAU -fnewbase -fsplitbase --exact-configuration --ghc-option=-fhide-source-paths
    Process exited with code: ExitFailure 1

**Comment by chessai** [comment]
Have you installed the pcre headers?

**Comment by chessai** [comment]
Also, you didn't paste the actual error. It says 'scroll up to its section to see the error'

**Comment by hegerard** [comment]
You are right.  After doing a pcre-devel install, the 'stack build' ended successfully.  
However I did not do it because  the instruction said "On macOS you'll need to install PCRE'.

**Comment by chessai** [comment]
> You are right. After doing a pcre-devel install, the 'stack build' ended successfully.
> However I did not do it because the instruction said "On macOS you'll need to install PCRE'.

Got it. I'll update the README to include that for linux as well. Thanks!
