### ISSUE TITLE
Failed to build docker image locally.

### ISSUE THREAD

**Issue by XinXia2019** [facebook/duckling#607]
Hey guys. I'm running into this error when building a docker image locally. Seems no permission. 

`Step 7/15 : RUN stack setup
 ---> Running in 824c6340f04b
Preparing to install GHC (tinfo6) to an isolated location.
This will not interfere with any system-level installation.
Preparing to download ghc-tinfo6-8.6.5 ...
Download expectation failure: HttpExceptionRequest Request {
  host                 = "downloads.haskell.org"
  port                 = 443
  secure               = True
  requestHeaders       = [("User-Agent","The Haskell Stack")]
  path                 = "/~ghc/8.6.5/ghc-8.6.5-x86_64-fedora27-linux.tar.xz"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (InternalException (HandshakeFailed Error_EOF))`

**Comment by chessai** [comment]
Hmmm, seems possible that it's transient. Does trying again yield the same results?

**Comment by XinXia2019** [comment]
Thanks @chessai . Yeah. Still the same results.

**Comment by XinXia2019** [comment]
Seems my laptop issue. Thanks for the help!

**Comment by chessai** [comment]
@XinXia2019 what was the specific issue? So I know in order to help others who may have the same problem.

**Comment by XinXia2019** [comment]
Sorry, @chessai. I cannot figure out the connection issue. I simply switched to another backup laptop and works just fine.
