### ISSUE TITLE
How can I send a reference point date in the API call? 

### ISSUE THREAD

**Issue by OrtalAshkenaziGong** [facebook/duckling#628]
Hi, 
How can I send a reference point date in the API call? For example, I would like to calculate next week from 1.1.2019 and not from today.
Is there a parameter I can add to the API call ? 
curl -XPOST http://0.0.0.0:8000/parse --data 'locale=en_US&text=....

**Comment by chessai** [comment]
This requires overriding assumptions, which is planned but not currently supported/in progress. Closing in favour of #29
