### ISSUE TITLE
operating duckling tool on windows 10

### ISSUE THREAD

**Issue by AyaFayed** [facebook/duckling#637]
when I try to run this tool I get this error
> setup.EXE: Missing dependencies on foreign libraries:
HsOpenSSL      > * Missing (or bad) header file: openssl/asn1.h
HsOpenSSL      > * Missing (or bad) C libraries: eay32, ssl
HsOpenSSL      > This problem can usually be solved by installing the system packages that
HsOpenSSL      > provide these libraries (you may need the "-dev" versions). If the libraries
HsOpenSSL      > are already installed but in a non-standard location then you can use the
HsOpenSSL      > flags --extra-include-dirs= and --extra-lib-dirs= to specify where they are.If
HsOpenSSL      > the library files do exist, it may contain errors that are caught by the C
HsOpenSSL      > compiler at the preprocessing stage. In this case you can re-run configure
HsOpenSSL      > with the verbosity flag -v3 to see the error messages.
HsOpenSSL      > If the header file does exist, it may contain errors that are caught by the C
HsOpenSSL      > compiler at the preprocessing stage. In this case you can re-run configure
HsOpenSSL      > with the verbosity flag -v3 to see the error messages.
 While building package HsOpenSSL-0.11.4.17 (scroll up to its section to see the error) using:
      C:\Users\LENOVO X250\AppData\Local\Temp\stack-23dd6aa4621714ae\HsOpenSSL-0.11.4.17\.stack-work\dist\e626a42b\setup\setup --builddir=.stack-work\dist\e626a42b configure --user --package-db=clear --package-db=global --package-db=C:\sr\snapshots\1894f21c\pkgdb --libdir=C:\sr\snapshots\1894f21c\lib --bindir=C:\sr\snapshots\1894f21c\bin --datadir=C:\sr\snapshots\1894f21c\share --libexecdir=C:\sr\snapshots\1894f21c\libexec --sysconfdir=C:\sr\snapshots\1894f21c\etc --docdir=C:\sr\snapshots\1894f21c\doc\HsOpenSSL-0.11.4.17 --htmldir=C:\sr\snapshots\1894f21c\doc\HsOpenSSL-0.11.4.17 --haddockdir=C:\sr\snapshots\1894f21c\doc\HsOpenSSL-0.11.4.17 --dependency=Cabal=Cabal-2.4.1.0-5rQrtDcYhR2LOcYye7obEr --dependency=base=base-4.12.0.0 --dependency=bytestring=bytestring-0.10.8.2 --dependency=network=network-2.8.0.1-41igyNI75uzGO9xrEXCykL --dependency=time=time-1.8.0.2 -f-fast-bignum -f-homebrew-openssl -f-macports-openssl -f-old-locale "--extra-include-dirs=C:\\Users\\LENOVO X250\\AppData\\Local\\Programs\\stack\\x86_64-windows\\msys2-20210604\\mingw64\\include" "--extra-lib-dirs=C:\\Users\\LENOVO X250\\AppData\\Local\\Programs\\stack\\x86_64-windows\\msys2-20210604\\mingw64\\lib" "--extra-lib-dirs=C:\\Users\\LENOVO X250\\AppData\\Local\\Programs\\stack\\x86_64-windows\\msys2-20210604\\mingw64\\bin" --exact-configuration --ghc-option=-fhide-source-paths
    Process exited with code: ExitFailure 1

**Comment by chessai** [comment]
Exactly how are you building and running duckling?

**Comment by AyaFayed** [comment]
I build and run it using stack

**Comment by chessai** [comment]
Can  you paste the commands you are using to build, and to run?

**Comment by AyaFayed** [comment]
C:duckling > stack build

**Comment by chessai** [comment]
Try on new master?

**Comment by AyaFayed** [comment]
now stack build is completed successfully but when I type this command as mentioned stack exec duckling-example-exe
I get this error:
duckling-example-exe.EXE: /etc/zoneinfo/: getDirectoryContents:findFirstFile: does not exist (The system cannot find the path specified.)

**Comment by chessai** [comment]
See https://github.com/facebook/duckling/issues/412

**Comment by AyaFayed** [comment]
C:\w2\duckling>stack exec duckling-example-exe
no port specified, defaulting to port 8000
Listening on http://0.0.0.0:8000

it has been like that nothing changing for over an hour is that normal?

**Comment by chessai** [comment]
> C:\w2\duckling>stack exec duckling-example-exe
> no port specified, defaulting to port 8000
> Listening on http://0.0.0.0:8000
> 
> it has been like that nothing changing for over an hour is that normal?

Yes, that's normal. It won't print anything unless you make a request.
