### ISSUE TITLE
Timezone data fails to load

### ISSUE THREAD

**Issue by danbulant** [facebook/duckling#640]
Trying to start on Manjaro (`stack exec duckling-example-exe`) results first in `/etc/zoneinfo` not found, after symlinking to `/usr/share/zoneinfo` I see the true error:
```
duckling-example-exe: /etc/zoneinfo/Zulu: invalid timezone file: no timezone found in OlsonData
```

**Comment by chessai** [comment]
Can you show what version of timezone-olson your duckling was built with?
I believe that version 0.2 fixed a bug for arch linux.

**Comment by danbulant** [comment]
I'm new to haskell (never used it before), just wanted to try out duckling for other project.

~~I don't know how to view that, but if anything, I installed (and built) duckling today, and stack as well, so there was no cache which could use older version. If 0.2 is installed by default, I should have it.~~

I just used `stack ls dependencies` according to quick google search, says `timezone-olson 0.1.9`. How can I update to 0.2?

**Comment by chessai** [comment]
#641 should fix this.

**Comment by chessai** [comment]
Can you try on latest master?

**Comment by danbulant** [comment]
Latest master fixes the issue.
