### ISSUE TITLE
[Time.TR] Forgot to add to test suite?

### ISSUE THREAD

**Issue by emlautarom1** [facebook/duckling#660]
Turkish corpus is not used at all, resulting in an empty classifier:

https://github.com/facebook/duckling/blob/84175d61d6f44d0db2abb42d67c6c4213762b64f/Duckling/Ranking/Classifiers/TR_XX.hs#L22

The cause is that the test suite ("corpus") is never used (the module `Duckling.Time.TR.Tests` is not even imported):

https://github.com/facebook/duckling/blob/84175d61d6f44d0db2abb42d67c6c4213762b64f/tests/Duckling/Time/Tests.hs#L53-L83

Said module is also not declared in the `duckling.cabal` file:

https://github.com/facebook/duckling/blob/84175d61d6f44d0db2abb42d67c6c4213762b64f/duckling.cabal#L1136-L1163

This is a trivial fix. There are some failing test cases though!

**Comment by chessai** [comment]
Would you like to prepare a PR for this?
