### ISSUE TITLE
Not Root docker container for Openshift cluster

### ISSUE THREAD

**Issue by bigsem89** [facebook/duckling#668]
Hi, i'm trying to move image to openshift. But there is permissions issue with nonroot user.

duckling-example-exe: log: createDirectory: permission denied (Permission denied)

Could you help with it?

**Comment by chessai** [comment]
> Hi, i'm trying to move image to openshift. But there is permissions issue with nonroot user.
> 
> duckling-example-exe: log: createDirectory: permission denied (Permission denied)
> 
> Could you help with it?

If you don't need access logging or error logging, I recommend just passing in `--no-access-log` and `--no-error-log` to the executable. That will circumvent any permission issues you're having. As for debugging general permission issues on OpenShift, I'm not familiar with the technology and it's out of scope for this issue tracker.

**Comment by zoobab** [comment]
Which directory does it tries to create? Even with verbose mode, it does not say which directory it tries to create:

```
I have no name!@stack-duckling-65c67cd69f-727jn:/$ duckling-example-exe -vv -p 8000
duckling-example-exe: log: createDirectory: permission denied (Permission denied)
```

**Comment by zoobab** [comment]
The directory is '/log'. Just make sure it is writable.
