### ISSUE TITLE
Return latent entities

### ISSUE THREAD

**Issue by patapizza** [facebook/duckling#73]
Sometimes, we might want to "force" a parse of `Time` from a text.
Typically, when responding to a bot that expects a `Time` alternative. There might be a use case for other dimensions as well, e.g. `Temperature`.

To cover these use cases, we'd like to ask Duckling to return latent entities.

**Comment by chinmay87** [comment]
Closed with https://github.com/facebook/duckling/commit/5ac990bbe2e87ea3be8080c0c918e9106c05be77
